//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class asrAg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asrAg()
        {
            this.asrAg_bmp = new HashSet<asrAg_bmp>();
            this.asrAg_changes = new HashSet<asrAg_changes>();
            this.asrAg_QMA = new HashSet<asrAg_QMA>();
        }
    
        public int pk_asrAg { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string interviewee { get; set; }
        public Nullable<int> fk_list_designerEngineer_planner { get; set; }
        public int fk_farmBusiness { get; set; }
        public string fk_asrType_code { get; set; }
        public string landChange { get; set; }
        public string landChange_note { get; set; }
        public string goalsChange { get; set; }
        public string goalsChange_note { get; set; }
        public string WFPEffective { get; set; }
        public string WFPEffective_note { get; set; }
        public string BMPsEffective { get; set; }
        public string BMPsEffective_note { get; set; }
        public string BMPsOMA { get; set; }
        public string BMPsOMA_note { get; set; }
        public string revision { get; set; }
        public string revision_note { get; set; }
        public string issues { get; set; }
        public string issues_note { get; set; }
        public string comment { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public string active { get; set; }
        public string inactive_crops { get; set; }
        public string inactive_animal { get; set; }
        public string inactive_landUtilization { get; set; }
        public string inactive_other { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<short> year { get; set; }
        public Nullable<int> fk_list_designerEngineer_assignTo { get; set; }
        public string fk_asrType_code_assigned { get; set; }
        public string easementInfoReq { get; set; }
        public string note { get; set; }
        public string revision_note_participant { get; set; }
        public string revisionReqd { get; set; }
        public string revisionReqd_reference { get; set; }
        public string forestryInfoReq { get; set; }
        public string CREPInfoReq { get; set; }
        public string F2MInfoReq { get; set; }
        public string hasSign { get; set; }
        public Nullable<int> farmRankingProfJudgement_eoh { get; set; }
        public string qma_CALF_req { get; set; }
        public string qma_CROP_req { get; set; }
        public string qma_GRZ_req { get; set; }
        public string qma_MANU_req { get; set; }
        public string qma_PEST_req { get; set; }
        public string qma_NMP_req { get; set; }
        public string qma_PFM_req { get; set; }
    
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual list_asrType list_asrType { get; set; }
        public virtual list_designerEngineer list_designerEngineer { get; set; }
        public virtual list_designerEngineer list_designerEngineer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asrAg_bmp> asrAg_bmp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asrAg_changes> asrAg_changes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asrAg_QMA> asrAg_QMA { get; set; }
    }
}
