//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class asrAg_changes
    {
        public int pk_asrAg_changes { get; set; }
        public int fk_asrAg { get; set; }
        public string tractField { get; set; }
        public Nullable<decimal> acres { get; set; }
        public string usage { get; set; }
        public string landowner { get; set; }
        public string fk_asrAgChanges_code_ownRent { get; set; }
        public string fk_asrAgChanges_code_addDelete { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
    
        public virtual asrAg asrAg { get; set; }
        public virtual list_asrAgChanges list_asrAgChanges { get; set; }
        public virtual list_asrAgChanges list_asrAgChanges1 { get; set; }
    }
}
