//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventRegistrant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eventRegistrant()
        {
            this.eventDateAttendance = new HashSet<eventDateAttendance>();
        }
    
        public int pk_eventRegistrant { get; set; }
        public int fk_event { get; set; }
        public int fk_participant { get; set; }
        public string watershed_based { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public string fk_eventRegistrantType_code { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> fk_farmBusiness { get; set; }
    
        public virtual @event @event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventDateAttendance> eventDateAttendance { get; set; }
        public virtual list_eventRegistrantType list_eventRegistrantType { get; set; }
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual participant participant { get; set; }
    }
}
