//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmBusinessAnimal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public farmBusinessAnimal()
        {
            this.farmBusinessAnimalAge = new HashSet<farmBusinessAnimalAge>();
        }
    
        public int pk_farmBusinessAnimal { get; set; }
        public int fk_farmBusiness { get; set; }
        public int fk_list_animal { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<decimal> AU_ro { get; set; }
        public Nullable<short> ASR_yr { get; set; }
    
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual list_animal list_animal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farmBusinessAnimalAge> farmBusinessAnimalAge { get; set; }
    }
}
