//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmBusinessTier1Animal
    {
        public int pk_farmBusinessTier1Animal { get; set; }
        public int fk_farmBusinessTier1 { get; set; }
        public int fk_list_animal { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> cnt { get; set; }
    
        public virtual farmBusinessTier1 farmBusinessTier1 { get; set; }
        public virtual list_animal list_animal { get; set; }
    }
}
