//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_wfp3_invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public form_wfp3_invoice()
        {
            this.form_wfp3_payment = new HashSet<form_wfp3_payment>();
        }
    
        public int pk_form_wfp3_invoice { get; set; }
        public int fk_form_wfp3 { get; set; }
        public System.DateTime date { get; set; }
        public string invoice_nbr { get; set; }
        public Nullable<decimal> amt { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
    
        public virtual form_wfp3 form_wfp3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<form_wfp3_payment> form_wfp3_payment { get; set; }
    }
}
