//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_wfp3_bid
    {
        public int pk_form_wfp3_bid { get; set; }
        public int fk_form_wfp3 { get; set; }
        public int fk_participant_contractor { get; set; }
        public decimal bid_amt { get; set; }
        public Nullable<decimal> modification_amt { get; set; }
        public string note { get; set; }
        public Nullable<byte> bid_rank { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public string bid_nbr_legacy { get; set; }
        public string bid_winner { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> bid_awarded { get; set; }
    
        public virtual form_wfp3 form_wfp3 { get; set; }
        public virtual participant participant { get; set; }
    }
}
