//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_trainingReqd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_trainingReqd()
        {
            this.list_trainingReqdPositionWAC = new HashSet<list_trainingReqdPositionWAC>();
            this.participantWAC_training = new HashSet<participantWAC_training>();
        }
    
        public string pk_trainingReqd_code { get; set; }
        public string title { get; set; }
        public Nullable<decimal> valid_yr { get; set; }
        public string description { get; set; }
        public Nullable<decimal> feePerPerson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_trainingReqdPositionWAC> list_trainingReqdPositionWAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participantWAC_training> participantWAC_training { get; set; }
    }
}
