//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_formsWAC
    {
        public string pk_formsWAC_code { get; set; }
        public string form { get; set; }
        public string fk_participantType_code { get; set; }
        public string fk_participantTypeSectorFolder_code { get; set; }
    
        public virtual list_participantType list_participantType { get; set; }
    }
}
