//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_basinCounty
    {
        public int pk_list_basinCounty { get; set; }
        public string fk_basin_code { get; set; }
        public int fk_list_countyNY { get; set; }
    
        public virtual list_basin list_basin { get; set; }
        public virtual list_countyNY list_countyNY { get; set; }
    }
}
