//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_participantTypeSectorFolder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_participantTypeSectorFolder()
        {
            this.documentArchive = new HashSet<documentArchive>();
        }
    
        public string pk_participantTypeSectorFolder_code { get; set; }
        public string fk_participantTypeSector_code { get; set; }
        public string folder { get; set; }
        public string WACFormsOnly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentArchive> documentArchive { get; set; }
        public virtual list_participantTypeSector list_participantTypeSector { get; set; }
    }
}
