//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_designerEngineerType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_designerEngineerType()
        {
            this.form_wfp2_version_tech = new HashSet<form_wfp2_version_tech>();
            this.form_wfp3_tech = new HashSet<form_wfp3_tech>();
            this.list_designerEngineerUsage = new HashSet<list_designerEngineerUsage>();
        }
    
        public string pk_designerEngineerType_code { get; set; }
        public string grouping { get; set; }
        public string formWFP3Tech { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<form_wfp2_version_tech> form_wfp2_version_tech { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<form_wfp3_tech> form_wfp3_tech { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_designerEngineerUsage> list_designerEngineerUsage { get; set; }
    }
}
