//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_encumbrance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_encumbrance()
        {
            this.bmp_ag_encumbrance = new HashSet<bmp_ag_encumbrance>();
            this.form_wfp3_encumbrance = new HashSet<form_wfp3_encumbrance>();
            this.form_wfp3_payment = new HashSet<form_wfp3_payment>();
            this.list_encumbranceProgram = new HashSet<list_encumbranceProgram>();
        }
    
        public string pk_encumbrance_code { get; set; }
        public string encumbrance { get; set; }
        public string active { get; set; }
        public Nullable<decimal> budget { get; set; }
        public string monitor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bmp_ag_encumbrance> bmp_ag_encumbrance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<form_wfp3_encumbrance> form_wfp3_encumbrance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<form_wfp3_payment> form_wfp3_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_encumbranceProgram> list_encumbranceProgram { get; set; }
    }
}
