//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_planner
    {
        public int pk_list_designerEngineer { get; set; }
        public string designerEngineer { get; set; }
        public string fk_agency_code { get; set; }
        public string title { get; set; }
    }
}
