//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_basin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_basin()
        {
            this.farmBusinessLandBaseInfo = new HashSet<farmBusinessLandBaseInfo>();
            this.list_basinCounty = new HashSet<list_basinCounty>();
            this.list_countyNYBasin = new HashSet<list_countyNYBasin>();
            this.property = new HashSet<property>();
        }
    
        public string pk_basin_code { get; set; }
        public string basin { get; set; }
        public string county { get; set; }
        public string priority { get; set; }
        public string EOH { get; set; }
        public string WOH { get; set; }
        public string eoh_highPriority { get; set; }
        public string eoh_lowPriority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farmBusinessLandBaseInfo> farmBusinessLandBaseInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_basinCounty> list_basinCounty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_countyNYBasin> list_countyNYBasin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property> property { get; set; }
    }
}
