//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class participantCommunication
    {
        public int pk_participantCommunication { get; set; }
        public int fk_participant { get; set; }
        public int fk_communication { get; set; }
        public string fk_communicationType_code { get; set; }
        public string fk_communicationUsage_code { get; set; }
        public Nullable<int> fk_organization { get; set; }
        public string extension { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string source { get; set; }
    
        public virtual communication communication { get; set; }
        public virtual list_communicationType list_communicationType { get; set; }
        public virtual list_communicationUsage list_communicationUsage { get; set; }
        public virtual organization organization { get; set; }
        public virtual participant participant { get; set; }
    }
}
