//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxParcelReference_farmID
    {
        public int OBJECTID { get; set; }
        public Nullable<int> FID_Ag_FarmLocations { get; set; }
        public string WAC_NO { get; set; }
        public string WAC_EASE { get; set; }
        public string CREP { get; set; }
        public string ADDRESS { get; set; }
        public string ZIP { get; set; }
        public string WAP { get; set; }
        public string FARMNAME { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string PHONE { get; set; }
        public string SF_ID { get; set; }
        public string FARM_USE { get; set; }
        public string INV { get; set; }
        public string NAME_OWNER { get; set; }
        public string NAME_OPERATOR { get; set; }
        public string BASIN { get; set; }
        public string SUBBASIN { get; set; }
        public string FARMTYPE { get; set; }
        public string FARMSTATUS { get; set; }
        public string SWIS { get; set; }
        public string COUNTY_SBL { get; set; }
        public string SBL { get; set; }
        public string PRINT_KEY { get; set; }
        public Nullable<decimal> ACRES { get; set; }
        public string ZIP_CODE { get; set; }
        public string ZIP_4 { get; set; }
        public string COUNTY { get; set; }
        public string CITY_TOWN { get; set; }
        public string VILLAGE { get; set; }
        public Nullable<short> TAX_YEAR { get; set; }
        public string CITY_STATE { get; set; }
        public string OWNR_NAME1 { get; set; }
        public string OWNR_NAME2 { get; set; }
        public string ADDR_NAME { get; set; }
        public string STREET { get; set; }
        public string NARRATIVE1 { get; set; }
        public string MAIL_ADDR1 { get; set; }
        public string MAIL_ADDR2 { get; set; }
        public Nullable<int> Shape { get; set; }
    }
}
