//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorFilesFarmPathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRoleObject
    {
        public int pk_userRoleObject { get; set; }
        public int fk_userRole { get; set; }
        public Nullable<int> fk_list_dataSector { get; set; }
    
        public virtual list_dataSector list_dataSector { get; set; }
        public virtual userRole userRole { get; set; }
    }
}
