//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgBmpTypeCode
    {
        public AgBmpTypeCode()
        {
            this.BmpBacklog = new HashSet<BmpBacklog>();
        }
    
        public int AgBmpTypeCodeId { get; set; }
        public string BmpType { get; set; }
        public string BmpTypeCode { get; set; }
        public bool IsDisabled { get; set; }
    
        public virtual ICollection<BmpBacklog> BmpBacklog { get; set; }
    }
}
