//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgBmpViabilityCode
    {
        public AgBmpViabilityCode()
        {
            this.bmp_ag = new HashSet<bmp_ag>();
        }
    
        public int AgBmpViabilityCodeId { get; set; }
        public string Viability { get; set; }
        public string ViabilityCode { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<bmp_ag> bmp_ag { get; set; }
    }
}
