//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class asrAg_QMA
    {
        public int pk_asrAg_QMA { get; set; }
        public int fk_asrAg { get; set; }
        public string fk_qmaType_code { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
    
        public virtual asrAg asrAg { get; set; }
        public virtual list_QMAType list_QMAType { get; set; }
    }
}
