//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class bmp_ag_funding
    {
        public int pk_bmp_ag_funding { get; set; }
        public int fk_bmp_ag { get; set; }
        public System.DateTime date { get; set; }
        public string fk_fundingSource_code { get; set; }
        public string fk_agencyFunding_code { get; set; }
        public decimal funding { get; set; }
        public string description { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public string bmp_id_new_legacy { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> fk_form_wfp2_version { get; set; }
        public string component_legacy { get; set; }
        public string fk_fundingPurpose_code { get; set; }
    
        public virtual bmp_ag bmp_ag { get; set; }
        public virtual form_wfp2_version form_wfp2_version { get; set; }
        public virtual list_agencyFunding list_agencyFunding { get; set; }
        public virtual list_fundingPurpose list_fundingPurpose { get; set; }
        public virtual list_fundingSource list_fundingSource { get; set; }
    }
}
