//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class bmp_ag_workloadSupport
    {
        public int pk_bmp_ag_workloadSupport { get; set; }
        public int fk_bmp_ag_workload { get; set; }
        public string fk_BMPWorkloadSupport_code { get; set; }
        public int fk_list_designerEngineer { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
    
        public virtual bmp_ag_workload bmp_ag_workload { get; set; }
        public virtual list_BMPWorkloadSupport list_BMPWorkloadSupport { get; set; }
        public virtual list_designerEngineer list_designerEngineer { get; set; }
    }
}
