//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class bmpAgAddExpressIntab
    {
        public Nullable<int> fk_farmBusiness { get; set; }
        public string fk_pollutant_category_code { get; set; }
        public string bmp_nbr { get; set; }
        public string descrip { get; set; }
        public Nullable<decimal> fk_bmpPractice_code { get; set; }
        public Nullable<decimal> units_planned { get; set; }
        public Nullable<decimal> est_plan_prior { get; set; }
        public Nullable<decimal> current_planning_estimate { get; set; }
        public string CREP { get; set; }
        public string fk_statusBMP_code { get; set; }
        public string fk_BMPSource_code { get; set; }
        public string location { get; set; }
        public string fk_revisionDescription_code { get; set; }
        public string fk_SAAssignType_code { get; set; }
        public Nullable<int> fk_supplementalAgreementTaxParcel { get; set; }
        public string fk_BMPTypeCode { get; set; }
        public string fk_BMPCode_code { get; set; }
        public string fk_BMPCREPH20_code { get; set; }
        public string issueStatement_wfp2 { get; set; }
        public string createFundingRecord { get; set; }
        public Nullable<int> pk_bmp_ag { get; set; }
        public Nullable<System.DateTime> fundingDate { get; set; }
        public Nullable<int> fk_form_wfp2_version { get; set; }
        public string fk_fundingPurpose_code { get; set; }
        public string fk_fundingSource_code { get; set; }
        public string fk_agencyFunding_code { get; set; }
        public string fk_encumbrance_code { get; set; }
        public Nullable<decimal> funding { get; set; }
        public string fundingDescription { get; set; }
        public string username { get; set; }
        public Nullable<int> resultCode { get; set; }
        public Nullable<System.DateTime> notificationSent { get; set; }
        public Nullable<short> nmcpYear { get; set; }
        public string error_text { get; set; }
    }
}
