//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmBusinessPriorOwner
    {
        public int pk_farmBusiness { get; set; }
        public string farmID { get; set; }
        public Nullable<int> pk_participant { get; set; }
        public string priorOwner { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
    }
}
