//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmBusiness
    {
        public farmBusiness()
        {
            this.BmpBacklog = new HashSet<BmpBacklog>();
            this.asrAg = new HashSet<asrAg>();
            this.bmp_ag = new HashSet<bmp_ag>();
            this.bmp_ag1 = new HashSet<bmp_ag>();
            this.bmp_ag2 = new HashSet<bmp_ag>();
            this.cropware = new HashSet<cropware>();
            this.eventRegistrant = new HashSet<eventRegistrant>();
            this.farmBusiness1 = new HashSet<farmBusiness>();
            this.farmBusiness11 = new HashSet<farmBusiness>();
            this.farmBusinessAnimal = new HashSet<farmBusinessAnimal>();
            this.farmBusinessAnimal2008 = new HashSet<farmBusinessAnimal2008>();
            this.farmBusinessASR = new HashSet<farmBusinessASR>();
            this.farmBusinessContact = new HashSet<farmBusinessContact>();
            this.farmBusinessCREP = new HashSet<farmBusinessCREP>();
            this.farmBusinessFAD = new HashSet<farmBusinessFAD>();
            this.farmBusinessLandBaseInfo = new HashSet<farmBusinessLandBaseInfo>();
            this.farmBusinessMail = new HashSet<farmBusinessMail>();
            this.farmBusinessNMCP = new HashSet<farmBusinessNMCP>();
            this.farmBusinessNMP = new HashSet<farmBusinessNMP>();
            this.farmBusinessNote = new HashSet<farmBusinessNote>();
            this.farmBusinessOperator = new HashSet<farmBusinessOperator>();
            this.farmBusinessOwner = new HashSet<farmBusinessOwner>();
            this.farmBusinessPlanner = new HashSet<farmBusinessPlanner>();
            this.farmBusinessQMA = new HashSet<farmBusinessQMA>();
            this.farmBusinessRevisionReqd = new HashSet<farmBusinessRevisionReqd>();
            this.farmBusinessStatus = new HashSet<farmBusinessStatus>();
            this.farmBusinessTaxParcel = new HashSet<farmBusinessTaxParcel>();
            this.farmBusinessTier1 = new HashSet<farmBusinessTier1>();
            this.farmBusinessType = new HashSet<farmBusinessType>();
            this.farmBusinessWLProject = new HashSet<farmBusinessWLProject>();
            this.form_wfp2 = new HashSet<form_wfp2>();
            this.form_wfp3 = new HashSet<form_wfp3>();
        }
    
        public int pk_farmBusiness { get; set; }
        public int fk_farmLand { get; set; }
        public string farmID { get; set; }
        public string prior_LF_FarmID { get; set; }
        public string fk_programWAC_code { get; set; }
        public string fk_farmSize_code { get; set; }
        public string farm_name { get; set; }
        public string fk_ownership_code { get; set; }
        public string type { get; set; }
        public Nullable<decimal> form_wfp2_total_plan_approved { get; set; }
        public Nullable<decimal> form_wfp2_total_crep_approved { get; set; }
        public string wac_program_fad { get; set; }
        public string wac_program_nonfad { get; set; }
        public string sold_farm { get; set; }
        public Nullable<short> farm_cnt { get; set; }
        public Nullable<short> subfarm_cnt { get; set; }
        public Nullable<short> multiple_farm_equivalents { get; set; }
        public string team { get; set; }
        public string fk_environmentalImpact_code { get; set; }
        public string IA_prior_to_implementation { get; set; }
        public string prior_implementation_commenced { get; set; }
        public string implementation_substantially_complete { get; set; }
        public Nullable<System.DateTime> implementation_substantially_complete_date { get; set; }
        public Nullable<System.DateTime> implementation_fully_complete_date { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> approved_date_legacy { get; set; }
        public string status_comment { get; set; }
        public string fk_mailingStatus_code { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string ownerStr_dnd { get; set; }
        public string supplementalAttachmentWFP2 { get; set; }
        public string EIN { get; set; }
        public string W9_filed { get; set; }
        public string planned { get; set; }
        public string CREP_capExempt { get; set; }
        public Nullable<decimal> guideline_curr { get; set; }
        public string fk_groupPI_code { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string FAD { get; set; }
        public string forestry { get; set; }
        public string easement { get; set; }
        public Nullable<decimal> ranking_ro { get; set; }
        public Nullable<System.DateTime> ranking_date_ro { get; set; }
        public string fk_status_code_orig { get; set; }
        public string fk_status_code_curr { get; set; }
        public Nullable<decimal> gps_id_legacy { get; set; }
        public Nullable<int> bmp_cnt_ro { get; set; }
        public string wfp1_signed { get; set; }
        public Nullable<System.DateTime> wfp0_signed { get; set; }
        public string wfp0 { get; set; }
        public string fk_dataReview_code { get; set; }
        public string dataReview_note { get; set; }
        public string farmToMarket { get; set; }
        public string taxParcelStr_dnd { get; set; }
        public Nullable<int> fk_farmBusiness_transferTo { get; set; }
        public Nullable<int> fk_farmBusiness_transferFrom { get; set; }
        public Nullable<System.DateTime> wfp1_signed_date { get; set; }
        public string ownerStrFL_dnd { get; set; }
        public string ownerStrLF_dnd { get; set; }
        public string priorOwner { get; set; }
        public string fk_easementType_code { get; set; }
    
        public virtual ICollection<BmpBacklog> BmpBacklog { get; set; }
        public virtual ICollection<asrAg> asrAg { get; set; }
        public virtual ICollection<bmp_ag> bmp_ag { get; set; }
        public virtual ICollection<bmp_ag> bmp_ag1 { get; set; }
        public virtual ICollection<bmp_ag> bmp_ag2 { get; set; }
        public virtual ICollection<cropware> cropware { get; set; }
        public virtual ICollection<eventRegistrant> eventRegistrant { get; set; }
        public virtual ICollection<farmBusiness> farmBusiness1 { get; set; }
        public virtual farmBusiness farmBusiness2 { get; set; }
        public virtual ICollection<farmBusiness> farmBusiness11 { get; set; }
        public virtual farmBusiness farmBusiness3 { get; set; }
        public virtual farmLand farmLand { get; set; }
        public virtual list_easementType list_easementType { get; set; }
        public virtual list_environmentalImpact list_environmentalImpact { get; set; }
        public virtual list_farmSize list_farmSize { get; set; }
        public virtual list_groupPI list_groupPI { get; set; }
        public virtual list_mailingStatus list_mailingStatus { get; set; }
        public virtual list_ownership list_ownership { get; set; }
        public virtual list_programWAC list_programWAC { get; set; }
        public virtual list_regionWAC list_regionWAC { get; set; }
        public virtual list_status list_status { get; set; }
        public virtual ICollection<farmBusinessAnimal> farmBusinessAnimal { get; set; }
        public virtual ICollection<farmBusinessAnimal2008> farmBusinessAnimal2008 { get; set; }
        public virtual ICollection<farmBusinessASR> farmBusinessASR { get; set; }
        public virtual ICollection<farmBusinessContact> farmBusinessContact { get; set; }
        public virtual ICollection<farmBusinessCREP> farmBusinessCREP { get; set; }
        public virtual ICollection<farmBusinessFAD> farmBusinessFAD { get; set; }
        public virtual ICollection<farmBusinessLandBaseInfo> farmBusinessLandBaseInfo { get; set; }
        public virtual ICollection<farmBusinessMail> farmBusinessMail { get; set; }
        public virtual ICollection<farmBusinessNMCP> farmBusinessNMCP { get; set; }
        public virtual ICollection<farmBusinessNMP> farmBusinessNMP { get; set; }
        public virtual ICollection<farmBusinessNote> farmBusinessNote { get; set; }
        public virtual ICollection<farmBusinessOperator> farmBusinessOperator { get; set; }
        public virtual ICollection<farmBusinessOwner> farmBusinessOwner { get; set; }
        public virtual ICollection<farmBusinessPlanner> farmBusinessPlanner { get; set; }
        public virtual ICollection<farmBusinessQMA> farmBusinessQMA { get; set; }
        public virtual ICollection<farmBusinessRevisionReqd> farmBusinessRevisionReqd { get; set; }
        public virtual ICollection<farmBusinessStatus> farmBusinessStatus { get; set; }
        public virtual ICollection<farmBusinessTaxParcel> farmBusinessTaxParcel { get; set; }
        public virtual ICollection<farmBusinessTier1> farmBusinessTier1 { get; set; }
        public virtual ICollection<farmBusinessType> farmBusinessType { get; set; }
        public virtual ICollection<farmBusinessWLProject> farmBusinessWLProject { get; set; }
        public virtual ICollection<form_wfp2> form_wfp2 { get; set; }
        public virtual ICollection<form_wfp3> form_wfp3 { get; set; }
    }
}
