//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_wfp3_paymentBMP
    {
        public int pk_form_wfp3_paymentBMP { get; set; }
        public int fk_form_wfp3_payment { get; set; }
        public int fk_form_wfp3_bmp { get; set; }
        public Nullable<decimal> amt { get; set; }
        public Nullable<decimal> amt_agencyFunding { get; set; }
        public string fk_agencyFunding_code { get; set; }
        public string component_legacy { get; set; }
        public string bmp_nbr_new_legacy { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string fk_statusBMP_Code { get; set; }
        public string note { get; set; }
        public Nullable<decimal> amt_total { get; set; }
        public Nullable<decimal> fk_bmpPractice_code { get; set; }
        public string fk_paymentStatus_code { get; set; }
        public string reimbursement { get; set; }
        public string purchaseNMCP { get; set; }
    
        public virtual form_wfp3_bmp form_wfp3_bmp { get; set; }
        public virtual form_wfp3_payment form_wfp3_payment { get; set; }
        public virtual list_bmpPractice list_bmpPractice { get; set; }
        public virtual list_agencyFunding list_agencyFunding { get; set; }
        public virtual list_paymentStatus list_paymentStatus { get; set; }
        public virtual list_statusBMP list_statusBMP { get; set; }
    }
}
