//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_wfp3_specification
    {
        public int pk_form_wfp3_specification { get; set; }
        public int fk_form_wfp3 { get; set; }
        public decimal fk_bmpPractice_code { get; set; }
        public string bid_reqd { get; set; }
        public Nullable<decimal> units { get; set; }
        public Nullable<decimal> bid { get; set; }
        public Nullable<decimal> cost_per_unit { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<decimal> ABC { get; set; }
        public Nullable<int> fk_form_wfp3_bmp { get; set; }
        public Nullable<int> sort_position { get; set; }
    
        public virtual form_wfp3 form_wfp3 { get; set; }
        public virtual form_wfp3_bmp form_wfp3_bmp { get; set; }
        public virtual list_bmpPractice list_bmpPractice { get; set; }
    }
}
