//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_wacPracticeCategory
    {
        public list_wacPracticeCategory()
        {
            this.list_bmpPractice = new HashSet<list_bmpPractice>();
        }
    
        public int pk_list_wacPracticeCategory { get; set; }
        public string category { get; set; }
    
        public virtual ICollection<list_bmpPractice> list_bmpPractice { get; set; }
    }
}
