//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_statusBMP
    {
        public list_statusBMP()
        {
            this.bmp_ag = new HashSet<bmp_ag>();
            this.bmp_ag_status = new HashSet<bmp_ag_status>();
            this.form_wfp3_paymentBMP = new HashSet<form_wfp3_paymentBMP>();
        }
    
        public string pk_statusBMP_code { get; set; }
        public string status { get; set; }
        public string payment { get; set; }
        public string statusTable { get; set; }
        public string workload { get; set; }
        public string lifespan_update { get; set; }
    
        public virtual ICollection<bmp_ag> bmp_ag { get; set; }
        public virtual ICollection<bmp_ag_status> bmp_ag_status { get; set; }
        public virtual ICollection<form_wfp3_paymentBMP> form_wfp3_paymentBMP { get; set; }
    }
}
