//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_communicationUsage
    {
        public list_communicationUsage()
        {
            this.participantCommunication = new HashSet<participantCommunication>();
        }
    
        public string pk_communicationUsage_code { get; set; }
        public string usage { get; set; }
        public string fk_communicationType_code { get; set; }
    
        public virtual list_communicationType list_communicationType { get; set; }
        public virtual ICollection<participantCommunication> participantCommunication { get; set; }
    }
}
