//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_townshipNY
    {
        public list_townshipNY()
        {
            this.property = new HashSet<property>();
        }
    
        public int pk_list_townshipNY { get; set; }
        public int fk_list_countyNY { get; set; }
        public string township { get; set; }
    
        public virtual list_countyNY list_countyNY { get; set; }
        public virtual ICollection<property> property { get; set; }
    }
}
