//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_fundingPurpose
    {
        public list_fundingPurpose()
        {
            this.bmp_ag_funding = new HashSet<bmp_ag_funding>();
        }
    
        public string pk_fundingPurpose_code { get; set; }
        public string purpose { get; set; }
    
        public virtual ICollection<bmp_ag_funding> bmp_ag_funding { get; set; }
    }
}
