//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_QMAType
    {
        public list_QMAType()
        {
            this.asrAg_QMA = new HashSet<asrAg_QMA>();
            this.farmBusinessQMA = new HashSet<farmBusinessQMA>();
        }
    
        public string pk_QMAType_code { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<asrAg_QMA> asrAg_QMA { get; set; }
        public virtual ICollection<farmBusinessQMA> farmBusinessQMA { get; set; }
    }
}
