//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempDefault
    {
        public string description { get; set; }
        public string fk_procurementType_code { get; set; }
        public string designer { get; set; }
        public string designer_title { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> contract_awarded_date { get; set; }
        public string drawing_nbr { get; set; }
        public string packageName { get; set; }
        public Nullable<System.DateTime> design_date { get; set; }
        public Nullable<System.DateTime> procurementPlan_date { get; set; }
        public string specialProvisions { get; set; }
        public string attachedSpecifications { get; set; }
        public Nullable<System.DateTime> install_from { get; set; }
        public Nullable<System.DateTime> install_to { get; set; }
        public string attachedPages_cnt { get; set; }
        public Nullable<int> fk_farmBusiness { get; set; }
        public Nullable<System.DateTime> section3_signature_date { get; set; }
        public Nullable<System.DateTime> section4_signature_date { get; set; }
        public Nullable<System.DateTime> section5_signature_date { get; set; }
        public Nullable<System.DateTime> certification_date { get; set; }
        public string fixedText { get; set; }
        public string fixedText2 { get; set; }
        public string message2_freeform { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public string CREP { get; set; }
        public Nullable<int> PK { get; set; }
    }
}
