//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusinessNMP
    {
        public int pk_farmBusiness { get; set; }
        public int pk_nmp { get; set; }
        public int pk_bmp_ag { get; set; }
        public string farmID { get; set; }
        public string farm_name { get; set; }
        public string ownerStrLF_dnd { get; set; }
        public string fk_status_code { get; set; }
        public string Farm_Status { get; set; }
        public string bmp_nbr { get; set; }
        public string description { get; set; }
        public string fk_statusBMP_code { get; set; }
        public string BMP_Status { get; set; }
        public Nullable<decimal> fk_bmpPractice_code { get; set; }
        public string NRCS_Practice { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string fk_pollutant_category_code { get; set; }
        public string Pollutant_Category { get; set; }
        public Nullable<int> acres_corn { get; set; }
        public Nullable<decimal> acres_planned { get; set; }
        public Nullable<short> AWEP_signup { get; set; }
        public string basic_plan { get; set; }
        public string bmp_nbr_nmp { get; set; }
        public string comment { get; set; }
        public string CREP { get; set; }
        public Nullable<short> crop_year { get; set; }
        public Nullable<short> crop_year_expiration { get; set; }
        public string enterprise_primary { get; set; }
        public string enterprise_secondary { get; set; }
        public string fk_followupNMP_code { get; set; }
        public Nullable<int> fk_list_designerEngineer_nmp { get; set; }
        public Nullable<int> fk_list_designerEngineer_nrcs { get; set; }
        public string fk_NMPStorage_code { get; set; }
        public Nullable<System.DateTime> fsa_release_date { get; set; }
        public Nullable<short> goal { get; set; }
        public Nullable<System.DateTime> manure_sample_date { get; set; }
        public string sampler { get; set; }
        public Nullable<short> sample_cnt { get; set; }
        public Nullable<System.DateTime> sample_date_most_recent { get; set; }
        public Nullable<short> sample_priority { get; set; }
        public Nullable<System.DateTime> spreader_calibration_date { get; set; }
        public string wfp1_signatures { get; set; }
        public Nullable<System.DateTime> WFP3_signature_date { get; set; }
        public Nullable<short> WFP3_year { get; set; }
    }
}
