//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFarmDocs
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_wfp2
    {
        public string Farm_ID { get; set; }
        public string Farm_Listing { get; set; }
        public string Landowner_s_and_or_Producer_s_Name { get; set; }
        public string county { get; set; }
        public byte version { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public Nullable<System.DateTime> setup_date { get; set; }
        public string Farm_Size { get; set; }
        public Nullable<decimal> Cost_Guideline { get; set; }
        public string Pollutant_I { get; set; }
        public string Pollutant_II { get; set; }
        public string Pollutant_III { get; set; }
        public string Pollutant_IV { get; set; }
        public string Pollutant_V { get; set; }
        public string Pollutant_V2_CREP { get; set; }
        public string Pollutant_VI { get; set; }
        public string Pollutant_VII { get; set; }
        public string Pollutant_VIII { get; set; }
        public string Pollutant_IX { get; set; }
        public string Pollutant_X { get; set; }
        public string Pollutant_XI { get; set; }
        public int fk_farmBusiness { get; set; }
        public Nullable<int> fk_supplementalAgreement { get; set; }
        public int pk_form_wfp2_version { get; set; }
        public int pk_form_wfp2 { get; set; }
        public string ownerStr_dnd { get; set; }
        public string taxParcelStr_dnd { get; set; }
        public Nullable<decimal> acresSA { get; set; }
        public string agreement_nbr_ro { get; set; }
    }
}
