//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllBmpsVw
    {
        public int fk_bmp_ag { get; set; }
        public int fk_farmBusiness { get; set; }
        public string bmp_nbr { get; set; }
        public int IsBacklog { get; set; }
        public string Bmp { get; set; }
        public string AgBmpDescriptorCode { get; set; }
        public string AgBmpDescriptor { get; set; }
        public string AgBmpQualifierCode { get; set; }
        public string Qualifier { get; set; }
        public Nullable<byte> QualifierVersion { get; set; }
        public string CompositBmpNumber { get; set; }
        public string AgBmpTypeCode { get; set; }
        public string AgBmpValidationCode { get; set; }
        public string AgBmpStatusCode { get; set; }
        public string Status { get; set; }
        public System.DateTime StatusDate { get; set; }
        public string description { get; set; }
        public Nullable<decimal> units_planned { get; set; }
        public Nullable<decimal> units_designed { get; set; }
        public Nullable<decimal> units_completed { get; set; }
        public string dimensions { get; set; }
        public string dimensions_designed { get; set; }
        public Nullable<decimal> est_plan_prior { get; set; }
        public Nullable<decimal> est_plan_rev { get; set; }
        public Nullable<decimal> design_cost { get; set; }
        public Nullable<decimal> final_modifications_cost { get; set; }
        public Nullable<decimal> final_cost { get; set; }
        public Nullable<System.DateTime> Completed_Date { get; set; }
        public Nullable<System.DateTime> CertDate { get; set; }
        public Nullable<decimal> fk_bmpPractice_code { get; set; }
        public string fk_pollutant_category_code { get; set; }
        public string fk_procurementType_code { get; set; }
        public string fk_statusBMP_code { get; set; }
        public Nullable<int> fk_programmaticRecord_code { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<short> WorkloadGrouping { get; set; }
        public Nullable<int> fk_farmBusinessWLProject { get; set; }
        public Nullable<int> fk_farmBusinessWLProjectBMP { get; set; }
        public Nullable<byte> version { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string fk_WFP2ApprovedBy_code { get; set; }
    }
}
