//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class bmp_ag_workload
    {
        public bmp_ag_workload()
        {
            this.bmp_ag_workloadSupport = new HashSet<bmp_ag_workloadSupport>();
        }
    
        public int pk_bmp_ag_workload { get; set; }
        public int fk_bmp_ag { get; set; }
        public Nullable<short> year { get; set; }
        public string fk_statusBMPWorkload_code { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<decimal> priority { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string fk_workloadNotation_code { get; set; }
        public string isValidBMP { get; set; }
        public string fk_agency_code { get; set; }
        public Nullable<decimal> design_est { get; set; }
        public string design_est_note { get; set; }
        public Nullable<decimal> contract_amt { get; set; }
        public Nullable<decimal> contract_amt_mod { get; set; }
        public Nullable<decimal> payment_FSANRCS { get; set; }
        public Nullable<decimal> payment_WAC { get; set; }
        public Nullable<System.DateTime> designed_date { get; set; }
        public Nullable<System.DateTime> outForBid_date { get; set; }
        public Nullable<System.DateTime> contracted_date { get; set; }
        public Nullable<System.DateTime> underConstruction_date { get; set; }
        public string note { get; set; }
        public string nrcs_addl { get; set; }
        public string contract_amt_note { get; set; }
        public string fk_agWorkloadFunding_code { get; set; }
        public Nullable<int> fk_form_wfp3 { get; set; }
        public Nullable<int> priorityTech { get; set; }
        public string fk_BMPWorkloadSortGroup_code { get; set; }
        public Nullable<System.DateTime> prog_engConsult { get; set; }
        public Nullable<System.DateTime> prog_survey { get; set; }
        public Nullable<System.DateTime> prog_inProg30 { get; set; }
        public Nullable<System.DateTime> prog_inProg60 { get; set; }
        public Nullable<System.DateTime> prog_inProg90 { get; set; }
        public Nullable<System.DateTime> prog_design95 { get; set; }
        public Nullable<System.DateTime> prog_readyForBid100 { get; set; }
        public Nullable<System.DateTime> prog_engConsult_done { get; set; }
        public Nullable<System.DateTime> prog_survey_done { get; set; }
        public Nullable<System.DateTime> prog_inProg30_done { get; set; }
        public Nullable<System.DateTime> prog_inProg60_done { get; set; }
        public Nullable<System.DateTime> prog_inProg90_done { get; set; }
        public Nullable<System.DateTime> prog_design95_done { get; set; }
    
        public virtual bmp_ag bmp_ag { get; set; }
        public virtual form_wfp3 form_wfp3 { get; set; }
        public virtual list_agency list_agency { get; set; }
        public virtual list_agWorkloadFunding list_agWorkloadFunding { get; set; }
        public virtual list_workloadNotation list_workloadNotation { get; set; }
        public virtual list_statusBMPWorkload list_statusBMPWorkload { get; set; }
        public virtual ICollection<bmp_ag_workloadSupport> bmp_ag_workloadSupport { get; set; }
        public virtual list_BMPWorkloadSortGroup list_BMPWorkloadSortGroup { get; set; }
    }
}
