//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class BmpBacklog
    {
        public int BmpBacklogId { get; set; }
        public Nullable<int> fk_bmp_ag { get; set; }
        public Nullable<int> fk_farmBusiness { get; set; }
        public Nullable<System.DateTime> BacklogSnapshotDate { get; set; }
        public Nullable<int> OriginalBmpTypeCode { get; set; }
        public string BacklogListBmp { get; set; }
        public string BacklogListDescription { get; set; }
        public string BacklogListPC { get; set; }
        public string BacklogListQualifier { get; set; }
        public Nullable<decimal> BacklogListCostEstimate { get; set; }
        public string MatchedBmp { get; set; }
        public Nullable<bool> BecameIrc { get; set; }
        public Nullable<bool> BecameBmp { get; set; }
    
        public virtual AgBmpTypeCode AgBmpTypeCode { get; set; }
        public virtual bmp_ag bmp_ag { get; set; }
        public virtual farmBusiness farmBusiness { get; set; }
    }
}
