//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class BmpCostsVw
    {
        public int fk_bmp_ag { get; set; }
        public Nullable<decimal> PlanningEstimate { get; set; }
        public Nullable<decimal> DesignEstimate { get; set; }
        public Nullable<decimal> FinalCost { get; set; }
        public Nullable<decimal> TotalFunding { get; set; }
        public Nullable<decimal> WacFunding { get; set; }
        public Nullable<decimal> OtherFunding { get; set; }
        public Nullable<int> YearFundingApproved { get; set; }
        public decimal WacPayments { get; set; }
        public decimal OtherPayments { get; set; }
        public decimal TotalPayments { get; set; }
        public Nullable<System.DateTime> FinalPaymentDate { get; set; }
    }
}
