//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventDateAttendance
    {
        public int pk_eventDateAttendance { get; set; }
        public int fk_eventDate { get; set; }
        public int fk_eventRegistrant { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
    
        public virtual eventDate eventDate { get; set; }
        public virtual eventRegistrant eventRegistrant { get; set; }
    }
}
