//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_wfp3
    {
        public form_wfp3()
        {
            this.bmp_ag_workload = new HashSet<bmp_ag_workload>();
            this.form_wfp31 = new HashSet<form_wfp3>();
            this.form_wfp311 = new HashSet<form_wfp3>();
            this.form_wfp3_bid = new HashSet<form_wfp3_bid>();
            this.form_wfp3_bmp = new HashSet<form_wfp3_bmp>();
            this.form_wfp3_encumbrance = new HashSet<form_wfp3_encumbrance>();
            this.form_wfp3_invoice = new HashSet<form_wfp3_invoice>();
            this.form_wfp3_modification = new HashSet<form_wfp3_modification>();
            this.form_wfp3_payment = new HashSet<form_wfp3_payment>();
            this.form_wfp3_specification = new HashSet<form_wfp3_specification>();
            this.form_wfp3_tech = new HashSet<form_wfp3_tech>();
        }
    
        public int pk_form_wfp3 { get; set; }
        public string description { get; set; }
        public string fk_procurementType_code { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> contract_awarded_date { get; set; }
        public string drawing_nbr { get; set; }
        public string packageName { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public string package_id { get; set; }
        public Nullable<System.DateTime> procurementPlan_date { get; set; }
        public string specialProvisions { get; set; }
        public Nullable<System.DateTime> install_from { get; set; }
        public Nullable<System.DateTime> install_to { get; set; }
        public string attachedPages_cnt { get; set; }
        public Nullable<int> fk_farmBusiness { get; set; }
        public Nullable<System.DateTime> section3_signature_date { get; set; }
        public Nullable<System.DateTime> section4_signature_date { get; set; }
        public Nullable<System.DateTime> section5_signature_date { get; set; }
        public Nullable<System.DateTime> certification_date { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string fk_formWFP3_fixedText_code { get; set; }
        public string message2_freeform { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public string fk_formWFP3_fixedText2_code { get; set; }
        public Nullable<System.DateTime> bid_deadline_date { get; set; }
        public string attachedSpecifications { get; set; }
        public Nullable<decimal> retainage { get; set; }
        public string packageSentToContractors { get; set; }
        public Nullable<System.DateTime> outForBid_date { get; set; }
        public Nullable<System.DateTime> design_date { get; set; }
        public Nullable<System.DateTime> construction_date { get; set; }
        public Nullable<int> fk_form_wfp3_transferredTo { get; set; }
        public Nullable<int> fk_form_wfp3_transferredFrom { get; set; }
        public string contractorStr_dnd { get; set; }
        public string packageNameFrom { get; set; }
    
        public virtual ICollection<bmp_ag_workload> bmp_ag_workload { get; set; }
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual list_procurementType list_procurementType { get; set; }
        public virtual ICollection<form_wfp3> form_wfp31 { get; set; }
        public virtual form_wfp3 form_wfp32 { get; set; }
        public virtual ICollection<form_wfp3> form_wfp311 { get; set; }
        public virtual form_wfp3 form_wfp33 { get; set; }
        public virtual ICollection<form_wfp3_bid> form_wfp3_bid { get; set; }
        public virtual ICollection<form_wfp3_bmp> form_wfp3_bmp { get; set; }
        public virtual ICollection<form_wfp3_encumbrance> form_wfp3_encumbrance { get; set; }
        public virtual ICollection<form_wfp3_invoice> form_wfp3_invoice { get; set; }
        public virtual ICollection<form_wfp3_modification> form_wfp3_modification { get; set; }
        public virtual ICollection<form_wfp3_payment> form_wfp3_payment { get; set; }
        public virtual ICollection<form_wfp3_specification> form_wfp3_specification { get; set; }
        public virtual ICollection<form_wfp3_tech> form_wfp3_tech { get; set; }
    }
}
