//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_regionWAC
    {
        public list_regionWAC()
        {
            this.farmBusiness = new HashSet<farmBusiness>();
            this.list_countyNY = new HashSet<list_countyNY>();
            this.list_wacLocation = new HashSet<list_wacLocation>();
            this.participant = new HashSet<participant>();
        }
    
        public string pk_regionWAC_code { get; set; }
        public string regionWAC { get; set; }
        public string basicUsage { get; set; }
    
        public virtual ICollection<farmBusiness> farmBusiness { get; set; }
        public virtual ICollection<list_countyNY> list_countyNY { get; set; }
        public virtual ICollection<list_wacLocation> list_wacLocation { get; set; }
        public virtual ICollection<participant> participant { get; set; }
    }
}
