//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_statusBMPWorkload
    {
        public list_statusBMPWorkload()
        {
            this.bmp_ag_workload = new HashSet<bmp_ag_workload>();
        }
    
        public string pk_statusBMPWorkload_code { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<bmp_ag_workload> bmp_ag_workload { get; set; }
    }
}
