//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_positionWAC
    {
        public list_positionWAC()
        {
            this.list_trainingReqdPositionWAC = new HashSet<list_trainingReqdPositionWAC>();
            this.participantWAC_evaluation = new HashSet<participantWAC_evaluation>();
            this.participantWAC_note = new HashSet<participantWAC_note>();
            this.participantWAC_position = new HashSet<participantWAC_position>();
            this.participantWAC_training = new HashSet<participantWAC_training>();
        }
    
        public string pk_positionWAC_code { get; set; }
        public string position { get; set; }
        public string fk_sectorHR_code { get; set; }
        public string exempt { get; set; }
        public string fk_classificationHR_code { get; set; }
        public string fk_EEO_code { get; set; }
        public Nullable<int> contactFAME { get; set; }
    
        public virtual list_classificationHR list_classificationHR { get; set; }
        public virtual list_EEO list_EEO { get; set; }
        public virtual list_sectorHR list_sectorHR { get; set; }
        public virtual ICollection<list_trainingReqdPositionWAC> list_trainingReqdPositionWAC { get; set; }
        public virtual ICollection<participantWAC_evaluation> participantWAC_evaluation { get; set; }
        public virtual ICollection<participantWAC_note> participantWAC_note { get; set; }
        public virtual ICollection<participantWAC_position> participantWAC_position { get; set; }
        public virtual ICollection<participantWAC_training> participantWAC_training { get; set; }
    }
}
