//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_status
    {
        public list_status()
        {
            this.farmBusiness = new HashSet<farmBusiness>();
            this.farmBusinessStatus = new HashSet<farmBusinessStatus>();
        }
    
        public string pk_status_code { get; set; }
        public string status { get; set; }
        public Nullable<byte> sort { get; set; }
    
        public virtual ICollection<farmBusiness> farmBusiness { get; set; }
        public virtual ICollection<farmBusinessStatus> farmBusinessStatus { get; set; }
    }
}
