//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_sectorHR
    {
        public list_sectorHR()
        {
            this.list_positionWAC = new HashSet<list_positionWAC>();
            this.list_sectorWAC = new HashSet<list_sectorWAC>();
        }
    
        public string pk_sectorHR_code { get; set; }
        public string sector { get; set; }
    
        public virtual ICollection<list_positionWAC> list_positionWAC { get; set; }
        public virtual ICollection<list_sectorWAC> list_sectorWAC { get; set; }
    }
}
