//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_dataSector
    {
        public list_dataSector()
        {
            this.userRoleObject = new HashSet<userRoleObject>();
        }
    
        public int pk_list_dataSector { get; set; }
        public string sector { get; set; }
        public string fk_sectorWAC_code { get; set; }
    
        public virtual list_sectorWAC list_sectorWAC { get; set; }
        public virtual ICollection<userRoleObject> userRoleObject { get; set; }
    }
}
