//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_BMPSource
    {
        public list_BMPSource()
        {
            this.bmp_ag = new HashSet<bmp_ag>();
        }
    
        public string pk_BMPSource_code { get; set; }
        public string source { get; set; }
    
        public virtual ICollection<bmp_ag> bmp_ag { get; set; }
    }
}
