//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_wacLocation
    {
        public list_wacLocation()
        {
            this.participantWAC = new HashSet<participantWAC>();
        }
    
        public string pk_wacLocation_code { get; set; }
        public string location { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string phone { get; set; }
    
        public virtual list_regionWAC list_regionWAC { get; set; }
        public virtual ICollection<participantWAC> participantWAC { get; set; }
    }
}
