//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_BMPWorkloadSupport
    {
        public list_BMPWorkloadSupport()
        {
            this.bmp_ag_workloadSupport = new HashSet<bmp_ag_workloadSupport>();
        }
    
        public string pk_BMPWorkloadSupport_code { get; set; }
        public string mode { get; set; }
    
        public virtual ICollection<bmp_ag_workloadSupport> bmp_ag_workloadSupport { get; set; }
    }
}
