//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_telecommuteSchedule
    {
        public list_telecommuteSchedule()
        {
            this.participantWAC = new HashSet<participantWAC>();
        }
    
        public string pk_telecommuteSchedule_code { get; set; }
        public string setting { get; set; }
        public Nullable<int> sort { get; set; }
    
        public virtual ICollection<participantWAC> participantWAC { get; set; }
    }
}
