//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class mailing
    {
        public mailing()
        {
            this.mailingDate = new HashSet<mailingDate>();
            this.mailingParticipant = new HashSet<mailingParticipant>();
            this.mailingParticipant1 = new HashSet<mailingParticipant>();
        }
    
        public int pk_mailing { get; set; }
        public string mailing1 { get; set; }
        public string note { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string bucket { get; set; }
    
        public virtual ICollection<mailingDate> mailingDate { get; set; }
        public virtual ICollection<mailingParticipant> mailingParticipant { get; set; }
        public virtual ICollection<mailingParticipant> mailingParticipant1 { get; set; }
    }
}
