//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bmp_ag_financial
    {
        public int pk_bmp_ag { get; set; }
        public int fk_farmBusiness { get; set; }
        public string bmp_nbr { get; set; }
        public string fk_statusBMP_code { get; set; }
        public Nullable<decimal> funding { get; set; }
        public Nullable<decimal> payment { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<int> pk_form_wfp3 { get; set; }
        public Nullable<int> fk_bmp_ag_ancestor { get; set; }
        public Nullable<decimal> est_plan_prior { get; set; }
        public string CREP { get; set; }
        public Nullable<int> fk_supplementalAgreementTaxParcel { get; set; }
    }
}
