//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bmp_ag_SA
    {
        public int pk_farmBusiness { get; set; }
        public int pk_bmp_ag { get; set; }
        public int pk_supplementalAgreementTaxParcel { get; set; }
        public int pk_supplementalAgreement { get; set; }
        public int pk_form_wfp3 { get; set; }
        public int pk_taxParcel { get; set; }
        public Nullable<int> pk_easementStewardship { get; set; }
        public string farmID { get; set; }
        public string fk_status_code_curr { get; set; }
        public string Farm_Owner_FL { get; set; }
        public string Farm_Owner_LF { get; set; }
        public string bmp_nbr { get; set; }
        public string description { get; set; }
        public string fk_statusBMP_code { get; set; }
        public string packageName { get; set; }
        public Nullable<System.DateTime> certification_date { get; set; }
        public string agreement_nbr_ro { get; set; }
        public System.DateTime agreement_date { get; set; }
        public string SA_Landowner_FL { get; set; }
        public string SA_Landowner_LF { get; set; }
        public string fk_list_swis { get; set; }
        public string county { get; set; }
        public string jurisdiction { get; set; }
        public string taxParcelID { get; set; }
        public string SBL { get; set; }
        public Nullable<decimal> acreage { get; set; }
        public string retired { get; set; }
        public string Tax_Parcel_Owner_LF { get; set; }
        public string DEP_id { get; set; }
        public string fk_statusEasement_code { get; set; }
        public string fk_easementSteward_code { get; set; }
    }
}
