//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_designerEngineer_usage
    {
        public int pk_list_designerEngineer { get; set; }
        public int pk_list_designerEngineerUsage { get; set; }
        public string designerEngineer { get; set; }
        public string fk_designerEngineerType_code { get; set; }
        public string Technical_Assignment { get; set; }
        public string active { get; set; }
        public string title { get; set; }
        public string designerEngineer_title { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string nickname { get; set; }
    }
}
