//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_QMA
    {
        public int pk_farmBusinessQMA { get; set; }
        public int pk_farmBusiness { get; set; }
        public Nullable<int> pk_farmBusinessQMATech { get; set; }
        public Nullable<int> fk_list_designerEngineer { get; set; }
        public string farmID { get; set; }
        public string Owner { get; set; }
        public string Operator { get; set; }
        public string bmp_nbr { get; set; }
        public string fk_QMAType_code { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Planner { get; set; }
        public string QMA_Type { get; set; }
        public string situation { get; set; }
        public Nullable<int> Visits_Est { get; set; }
        public Nullable<int> Hours_Est { get; set; }
        public int Visits_Actual { get; set; }
        public decimal Hours_Actual { get; set; }
        public string Completed { get; set; }
        public string Expr1 { get; set; }
        public string goals { get; set; }
        public string impactSummary { get; set; }
        public Nullable<int> fk_bmp_ag { get; set; }
    }
}
