//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_form_wfp3_BMP
    {
        public int pk_form_wfp3 { get; set; }
        public int pk_farmBusiness { get; set; }
        public int pk_form_wfp3_bmp { get; set; }
        public int pk_bmp_ag { get; set; }
        public string farmID { get; set; }
        public string packageName { get; set; }
        public string CompositBmpNum { get; set; }
        public string fk_statusBMP_code { get; set; }
        public string Status_BMP { get; set; }
        public string fk_unit_code { get; set; }
        public Nullable<decimal> est_plan_prior { get; set; }
        public Nullable<decimal> est_plan_rev { get; set; }
        public Nullable<decimal> design_cost { get; set; }
        public Nullable<decimal> units_designed { get; set; }
        public Nullable<decimal> units_completed { get; set; }
        public Nullable<decimal> final_cost { get; set; }
        public Nullable<decimal> fk_bmpPractice_code { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string createdProgrammatically_ro { get; set; }
    }
}
