//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_LBI_acreageAbridged
    {
        public int fk_farmBusiness { get; set; }
        public string mode { get; set; }
        public decimal acre { get; set; }
    }
}
