//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusinessWorkloadProjectBMP_okToPick
    {
        public int pk_farmBusiness { get; set; }
        public int pk_bmp_ag { get; set; }
        public string farmID { get; set; }
        public string bmp_nbr { get; set; }
        public string description { get; set; }
        public string fk_statusBMP_code { get; set; }
        public string Status_BMP { get; set; }
    }
}
