//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusinessAttributes
    {
        public int pk_farmBusiness { get; set; }
        public string farmID { get; set; }
        public string FarmSize { get; set; }
        public string FarmName { get; set; }
        public string FarmOwner { get; set; }
        public string FarmOwnerAll { get; set; }
        public string FarmOperator { get; set; }
        public string fk_groupPI_code { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string StatusCode { get; set; }
        public string Status { get; set; }
        public string address { get; set; }
        public string CityZip { get; set; }
    }
}
