//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_address
    {
        public int pk_farmBusiness { get; set; }
        public int pk_farmLand { get; set; }
        public string farmID { get; set; }
        public string farm_name { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string fk_status_code { get; set; }
        public string address_farm { get; set; }
        public string csz_farm { get; set; }
        public string zip_farm { get; set; }
        public string OwnerFL { get; set; }
        public string OwnerLF { get; set; }
        public string address_owner { get; set; }
        public string csz_owner { get; set; }
        public string zip_owner { get; set; }
    }
}
