//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusinessBMP_NMP
    {
        public int pk_farmBusiness { get; set; }
        public int pk_bmp_ag { get; set; }
        public string farmID { get; set; }
        public string farm_name { get; set; }
        public string ownerStrLF_dnd { get; set; }
        public string fk_status_code { get; set; }
        public string Farm_Status { get; set; }
        public string bmp_nbr { get; set; }
        public string description { get; set; }
        public string fk_statusBMP_code { get; set; }
        public string BMP_Status { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string fk_pollutant_category_code { get; set; }
        public Nullable<decimal> fk_bmpPractice_code { get; set; }
        public string NRCS_WAC_Practice { get; set; }
        public string Pollutant_Category { get; set; }
        public string bmp_descrip { get; set; }
        public Nullable<int> fk_bmp_ag_nmp { get; set; }
        public string fk_regionWAC_code { get; set; }
    }
}
