//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_form_wfp3_BMPPayment_summary
    {
        public int fk_form_wfp3 { get; set; }
        public int fk_bmp_ag { get; set; }
        public string bmp_nbr { get; set; }
        public Nullable<decimal> bmp_paid_total { get; set; }
    }
}
