//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_form_wfp3_paymentBMP_NMCP
    {
        public int pk_form_wfp3_paymentBMP { get; set; }
        public int pk_form_wfp3_bmp { get; set; }
        public int fk_form_wfp3 { get; set; }
        public int pk_bmp_ag { get; set; }
        public int pk_farmBusiness { get; set; }
        public Nullable<int> fk_participant_payee { get; set; }
        public string farmID { get; set; }
        public string bmp_nbr { get; set; }
        public string description { get; set; }
        public Nullable<decimal> fk_bmpPractice_code { get; set; }
        public string practice { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string payee_FL { get; set; }
        public string payee_LF { get; set; }
        public string purchaseNMCP { get; set; }
        public Nullable<decimal> amt { get; set; }
        public Nullable<decimal> amt_agencyFunding { get; set; }
    }
}
