//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_phoneCell
    {
        public int pk_farmBusiness { get; set; }
        public Nullable<int> fk_participant { get; set; }
        public Nullable<int> pk_communication { get; set; }
        public string farmid { get; set; }
        public string Participant { get; set; }
        public string ParticipantFL { get; set; }
        public string Mode { get; set; }
        public string Type { get; set; }
        public string Number { get; set; }
        public string master { get; set; }
        public string active { get; set; }
        public string fk_communicationType_code { get; set; }
        public string fk_communicationUsage_code { get; set; }
    }
}
