//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_taxParcel
    {
        public Nullable<int> pk_farmBusinessTaxParcel { get; set; }
        public int pk_farmBusiness { get; set; }
        public Nullable<int> pk_taxParcel { get; set; }
        public string farmID { get; set; }
        public string farm_name { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string fk_status_code_curr { get; set; }
        public string fk_farmSize_code { get; set; }
        public string ownerLF_farm { get; set; }
        public string ownerFL_farm { get; set; }
        public string taxParcelID { get; set; }
        public string SBL { get; set; }
        public string fk_list_swis { get; set; }
        public string jurisdiction { get; set; }
        public string county { get; set; }
        public Nullable<decimal> acreage { get; set; }
        public string owner_TP { get; set; }
        public Nullable<short> taxRollYear { get; set; }
        public string retired { get; set; }
        public string OWNR_NAME1 { get; set; }
        public string OWNR_NAME2 { get; set; }
    }
}
