//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_CREPH20System
    {
        public int fk_farmBusiness { get; set; }
        public int pk_bmp_ag { get; set; }
        public string bmp_nbr { get; set; }
        public string description { get; set; }
        public string CREP { get; set; }
        public string fk_BMPCREPH20_code { get; set; }
        public string type { get; set; }
        public string practice { get; set; }
        public Nullable<int> fk_supplementalAgreement { get; set; }
    }
}
