//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_form_wfp3_paymentBMP_paymentStatus
    {
        public System.DateTime date { get; set; }
        public string CompositBmpNum { get; set; }
        public Nullable<decimal> amt { get; set; }
        public decimal amt_agencyFunding { get; set; }
        public string fk_agencyFunding_code { get; set; }
        public string otherAgencyFunding { get; set; }
        public string status { get; set; }
        public string FarmID { get; set; }
        public string fk_paymentStatus_code { get; set; }
        public string fk_statusBMP_Code { get; set; }
        public string packageName { get; set; }
        public string encumbrance_id { get; set; }
        public int pk_form_wfp3_paymentBMP { get; set; }
        public int fk_form_wfp3_payment { get; set; }
        public int fk_form_wfp3 { get; set; }
        public int fk_form_wfp3_bmp { get; set; }
        public int pk_bmp_ag { get; set; }
        public string check_nbr { get; set; }
        public Nullable<decimal> amtTotal { get; set; }
        public Nullable<int> fk_participant_payee { get; set; }
        public string fullname_FL_dnd { get; set; }
        public string fullname_LF_dnd { get; set; }
    }
}
