//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_groupPlanners
    {
        public string pk_groupPI_code { get; set; }
        public int pk_list_groupPIMember { get; set; }
        public int pk_list_designerEngineer { get; set; }
        public string Group { get; set; }
        public string designerEngineer { get; set; }
        public string nickname { get; set; }
        public string active_lde { get; set; }
        public string groupLeader { get; set; }
        public string @float { get; set; }
    }
}
