//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_SA
    {
        public int pk_farmBusiness { get; set; }
        public int pk_taxParcel { get; set; }
        public string farmID { get; set; }
        public string agreement_nbr_ro { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public Nullable<decimal> acreage { get; set; }
        public string fk_list_swis { get; set; }
        public string taxParcelID { get; set; }
        public string county { get; set; }
        public string jurisdiction { get; set; }
        public string ownerStr_dnd { get; set; }
    }
}
