//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_currentVersion
    {
        public int fk_farmBusiness { get; set; }
        public Nullable<byte> Version { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<System.DateTime> SetUp { get; set; }
        public Nullable<int> fk_supplementalAgreement { get; set; }
        public int pk_form_wfp2 { get; set; }
    }
}
