//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_ownerOperator
    {
        public int pk_farmBusiness { get; set; }
        public Nullable<int> pk_farmBusinessOwner { get; set; }
        public Nullable<int> fk_participant { get; set; }
        public string active { get; set; }
        public string master { get; set; }
        public string farmID { get; set; }
        public string farm_name { get; set; }
        public string OwnerFL { get; set; }
        public string OwnerLF { get; set; }
        public string fullname_FL_dnd { get; set; }
        public string fullname_LF_dnd { get; set; }
        public string source { get; set; }
        public string fk_farmSize_code { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string fk_status_code_curr { get; set; }
    }
}
