//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_planner
    {
        public string farmID { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string designerEngineer { get; set; }
        public string nickname { get; set; }
        public string fk_agency_code { get; set; }
        public string name { get; set; }
        public string groupLeader { get; set; }
        public int pk_farmBusiness { get; set; }
        public int fk_list_designerEngineer { get; set; }
        public string fk_groupPI_code { get; set; }
    }
}
