//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_farmBusiness_NMCP
    {
        public int pk_farmBusiness { get; set; }
        public int pk_farmBusinessNMCP { get; set; }
        public string farmID { get; set; }
        public string farm_name { get; set; }
        public string ownerStrLF_dnd { get; set; }
        public short year { get; set; }
        public Nullable<decimal> eligible_amt { get; set; }
        public Nullable<decimal> credit_amt { get; set; }
        public string note { get; set; }
        public Nullable<decimal> AU { get; set; }
        public Nullable<decimal> acreage { get; set; }
        public string fk_status_code { get; set; }
        public string Farm_Status { get; set; }
        public Nullable<int> fk_bmp_ag { get; set; }
        public string description { get; set; }
        public string bmp_nbr { get; set; }
        public Nullable<decimal> funding { get; set; }
        public Nullable<decimal> payment { get; set; }
        public Nullable<int> pk_bmp_ag { get; set; }
    }
}
