//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_interestType
    {
        public string interest { get; set; }
        public string participantType { get; set; }
        public string fk_participantType_code { get; set; }
        public int pk_list_interest { get; set; }
        public int pk_list_interestType { get; set; }
    }
}
