//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mailingDateRSVPNameCard
    {
        public int pk_mailingDateRSVPAttendee { get; set; }
        public string namecard { get; set; }
        public int pk_mailing { get; set; }
        public string mailing { get; set; }
        public int pk_mailingDate { get; set; }
        public System.DateTime dateSent { get; set; }
        public int pk_mailingDateRSVP { get; set; }
        public Nullable<int> cnt { get; set; }
        public Nullable<decimal> donation { get; set; }
        public string groupSponsor { get; set; }
        public string fullname_FL_dnd { get; set; }
        public string fullname_LF_dnd { get; set; }
        public int pk_participant { get; set; }
    }
}
