//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mailing_participant
    {
        public int pk_mailing { get; set; }
        public int pk_mailingParticipant { get; set; }
        public int pk_participant { get; set; }
        public string mailing { get; set; }
        public string nameLF { get; set; }
        public string nameFL { get; set; }
        public string email { get; set; }
        public string fk_mailingStatus_code { get; set; }
        public string doNotMail { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string csz_ro { get; set; }
        public string fk_zipcode { get; set; }
        public Nullable<int> fk_list_countyNY { get; set; }
        public Nullable<int> fk_list_townshipNY { get; set; }
        public Nullable<int> fk_AMLPriority_code { get; set; }
        public Nullable<int> maxAttend { get; set; }
        public string greeting { get; set; }
        public string active { get; set; }
        public Nullable<int> fk_mailing_transferFrom { get; set; }
    }
}
