//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_nmp
    {
        public string farmID { get; set; }
        public string farmname { get; set; }
        public string programWAC { get; set; }
        public string farmSize { get; set; }
        public string needs_nmp { get; set; }
        public string basic_plan { get; set; }
        public string followup { get; set; }
        public string EQIP { get; set; }
        public string nmp_credit { get; set; }
        public string storage { get; set; }
        public string Status { get; set; }
        public string planner_nrcs { get; set; }
        public string planner_nmp { get; set; }
        public string CREP { get; set; }
        public string bmp_nbr_nmp { get; set; }
        public string enterprise_primary { get; set; }
        public string enterprise_secondary { get; set; }
        public decimal animal_units { get; set; }
        public decimal acres_planned { get; set; }
        public int acres_corn { get; set; }
        public Nullable<short> goal { get; set; }
        public short crop_year { get; set; }
        public short crop_year_expiration { get; set; }
        public string operationsMaintenance_signature_date { get; set; }
        public string WFP3_signature_date { get; set; }
        public string sample_date_most_recent { get; set; }
        public short WFP3_year { get; set; }
        public short sample_cnt { get; set; }
        public short sample_priority { get; set; }
        public string sampler { get; set; }
        public string fsa_release_date { get; set; }
        public string nmp_workshop_date { get; set; }
        public string wfp1_signatures { get; set; }
        public string spreader_calibration_date { get; set; }
        public string comment { get; set; }
        public string manure_sample_date { get; set; }
    }
}
