//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payments
    {
        public string sector { get; set; }
        public string fk_regionWAC_code { get; set; }
        public int PK { get; set; }
        public string ID { get; set; }
        public Nullable<int> fk_participant_payee { get; set; }
        public string Payee { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> amt { get; set; }
        public string check_nbr { get; set; }
        public string Project { get; set; }
    }
}
