//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_participantWAC
    {
        public int pk_participantWAC { get; set; }
        public int pk_participant { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string Employee { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string Address { get; set; }
        public string CSZ { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
        public string email { get; set; }
        public string PhoneCellStr { get; set; }
        public string Emergency_Contact { get; set; }
        public string Emergency_Contact_Relationship { get; set; }
        public string race { get; set; }
        public string allergies { get; set; }
        public string Marital_Status { get; set; }
        public string Work_Phone { get; set; }
        public string phone_ext { get; set; }
        public string hireLetter { get; set; }
        public string resume { get; set; }
        public string conflictOfInterest { get; set; }
        public string recdManual { get; set; }
        public string LENS { get; set; }
        public string workSchedule { get; set; }
        public string confidentialityAgreement { get; set; }
        public string personalInfoSheet { get; set; }
        public Nullable<System.DateTime> TeleCommute_Start { get; set; }
        public Nullable<System.DateTime> TeleCommute_End { get; set; }
        public string SLT { get; set; }
        public string fieldStaff { get; set; }
        public string Data_Missing { get; set; }
        public string TeleCommute_Expired { get; set; }
        public string fk_wacLocation_code { get; set; }
        public string location { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public string fk_EEO_code { get; set; }
        public string classification { get; set; }
        public string fk_sectorHR_code { get; set; }
        public string sector { get; set; }
        public string fk_classificationHR_code { get; set; }
        public string classificationHR { get; set; }
        public string flexSchedule { get; set; }
        public Nullable<System.DateTime> StartGlobal { get; set; }
        public Nullable<System.DateTime> FinishGlobal { get; set; }
        public string fk_telecommuteSchedule_code { get; set; }
        public string fk_NWD_code { get; set; }
        public string NWD_Schedule { get; set; }
        public string TeleCommute_Schedule { get; set; }
        public string currentEmployee { get; set; }
        public string fullname_FL_dnd { get; set; }
        public string PPE { get; set; }
    }
}
