//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_participant
    {
        public int pk_participant { get; set; }
        public string Mailing_Status { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string org { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string cell { get; set; }
        public string email { get; set; }
        public string fullname_FL_dnd { get; set; }
        public string fullname_LF_dnd { get; set; }
        public string csz_ro { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string DBA { get; set; }
    }
}
