//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_participant_DR
    {
        public int pk_participant { get; set; }
        public string Participant { get; set; }
        public string Organization { get; set; }
        public string Address { get; set; }
        public string City_State_Zip { get; set; }
        public string County { get; set; }
        public string Township { get; set; }
        public string Mailing_Status { get; set; }
        public string Data_Review { get; set; }
        public string Is_Organization { get; set; }
        public string fk_mailingStatus_code { get; set; }
        public string fk_dataReview_code { get; set; }
    }
}
