//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_participantWAC_training
    {
        public int pk_participantWAC { get; set; }
        public int pk_participant { get; set; }
        public string Employee { get; set; }
        public int pk_participantWAC_training { get; set; }
        public string fk_fiscalYear_code { get; set; }
        public string FY_Training { get; set; }
        public string FY_Active { get; set; }
        public string fk_trainingReqd_code { get; set; }
        public string Training { get; set; }
        public string fk_positionWAC_code { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string note { get; set; }
        public string fk_classificationHR_code { get; set; }
        public string HR_Classification { get; set; }
        public string fk_EEO_code { get; set; }
        public string EEO_Classification { get; set; }
        public string fk_sectorHR_code { get; set; }
        public string HR_Sector { get; set; }
        public string exempt { get; set; }
        public Nullable<decimal> valid_yr { get; set; }
        public Nullable<decimal> TrainingCost { get; set; }
    }
}
