//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rangeType
    {
        public string pk_rangeType_code { get; set; }
        public int pk_list_rangeTypeMinMax { get; set; }
        public string descrip { get; set; }
        public string descriptor { get; set; }
        public string min { get; set; }
        public string max { get; set; }
    }
}
