//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_supplementalAgreement
    {
        public string farmID { get; set; }
        public string bmp_nbr { get; set; }
        public Nullable<decimal> est_plan_prior { get; set; }
        public Nullable<decimal> est_plan_rev { get; set; }
        public string Farm_BMP_Active { get; set; }
        public System.DateTime agreement_date { get; set; }
        public string agreement_nbr_ro { get; set; }
        public Nullable<System.DateTime> SA_Cancelled { get; set; }
        public int fk_taxParcel { get; set; }
        public Nullable<System.DateTime> SA_TP_Cancelled { get; set; }
        public string taxParcelID { get; set; }
        public string SBL { get; set; }
        public Nullable<decimal> acreage { get; set; }
        public string Farm_Owner { get; set; }
        public string Tax_Parcel_Owner { get; set; }
        public string Tax_Parcel_BMPs { get; set; }
        public int pk_supplementalAgreement { get; set; }
        public int pk_supplementalAgreementTaxParcel { get; set; }
        public Nullable<int> pk_bmp_ag { get; set; }
        public Nullable<int> pk_farmBusiness { get; set; }
        public int pk_taxParcel { get; set; }
        public string fk_SAAssignType_code { get; set; }
        public string fk_pollutant_category_code { get; set; }
    }
}
