//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_supplementalAgreement_farmID_TPO
    {
        public int pk_farmBusiness { get; set; }
        public string farmID { get; set; }
        public int fk_participant { get; set; }
    }
}
