//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_taxParcel_associations
    {
        public string source { get; set; }
        public int PK { get; set; }
        public string Label { get; set; }
        public string TableGo { get; set; }
        public int TablePK { get; set; }
    }
}
