//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_taxParcel_jurisdiction
    {
        public string county { get; set; }
        public string Jurisdiction { get; set; }
        public int pk_list_countyNY { get; set; }
        public string SWIS { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string jurisdiction_noSWIS { get; set; }
    }
}
