//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_taxParcel_owner
    {
        public int pk_taxParcel { get; set; }
        public int pk_participant { get; set; }
        public string fullname_FL_dnd { get; set; }
        public string fullname_LF_dnd { get; set; }
        public string fk_list_swis { get; set; }
        public string taxParcelID { get; set; }
        public string SBL { get; set; }
        public Nullable<decimal> acreage { get; set; }
        public string retired { get; set; }
        public string county { get; set; }
        public Nullable<int> pk_list_countyNY { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public int pk_taxParcelOwner { get; set; }
        public string note { get; set; }
        public string active { get; set; }
    }
}
