//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_taxParcel_DEP
    {
        public int PK_Fame { get; set; }
        public string SWIS { get; set; }
        public string SBL { get; set; }
        public string County_FAME { get; set; }
        public string jurisdiction { get; set; }
        public string PrintKey_FAME { get; set; }
        public string Owner_FAME { get; set; }
        public string PrintKey_DEP { get; set; }
        public Nullable<decimal> Acreage_DEP { get; set; }
        public string Owner_DEP { get; set; }
        public string County_DEP { get; set; }
        public string City_Town_DEP { get; set; }
        public int pk_taxParcel { get; set; }
    }
}
