//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_wfp3_bid
    {
        public string Farm_No_ { get; set; }
        public string Farm_Listing { get; set; }
        public string Package_Description { get; set; }
        public string Package_Name { get; set; }
        public string Contractor_1 { get; set; }
        public string Contractor_1_Address { get; set; }
        public string Contractor_1_City_State { get; set; }
        public string Contractor_1_Phone { get; set; }
        public string Contractor_1_Bid_Amt { get; set; }
        public string Contractor_2 { get; set; }
        public string Contractor_2_Address { get; set; }
        public string Contractor_2_City_State { get; set; }
        public string Contractor_2_Phone { get; set; }
        public string Contractor_2_Bid_Amt { get; set; }
        public string Contractor_3 { get; set; }
        public string Contractor_3_Address { get; set; }
        public string Contractor_3_City_State { get; set; }
        public string Contractor_3_Phone { get; set; }
        public string Contractor_3_Bid_Amt { get; set; }
        public int pk_form_wfp3 { get; set; }
    }
}
