//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_wfp5C
    {
        public string Farm_No_ { get; set; }
        public string Farm_Listing { get; set; }
        public string Participant_Name { get; set; }
        public string Participant_Address { get; set; }
        public string Participant_City_State { get; set; }
        public string Participant_Telephone { get; set; }
        public string Project_Location { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public string Project_Description { get; set; }
        public string BMP__ { get; set; }
        public string Contractor_Name { get; set; }
    }
}
