//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_wfp2_version_SA
    {
        public int pk_farmBusiness { get; set; }
        public int pk_form_wfp2_version { get; set; }
        public int pk_form_wfp2 { get; set; }
        public Nullable<int> fk_supplementalAgreement { get; set; }
        public string farmID { get; set; }
        public string Revision { get; set; }
        public string Approved { get; set; }
        public string Revision_Status { get; set; }
        public byte version { get; set; }
        public string agreement_nbr_ro { get; set; }
        public string ownerStr_dnd { get; set; }
        public string taxParcelStr_dnd { get; set; }
        public string ownerStrFL_dnd { get; set; }
    }
}
