//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_wfp2_bmp
    {
        public string Agreement_No_ { get; set; }
        public string Farm_Listing { get; set; }
        public string C_ { get; set; }
        public string location { get; set; }
        public string Name__Life_Span__ { get; set; }
        public string NRCS_WAC_Code { get; set; }
        public string Units_Planned { get; set; }
        public decimal Prior_Planning_Estimate { get; set; }
        public Nullable<decimal> Revised_Planning_Estimate { get; set; }
        public decimal Funds_Requested { get; set; }
        public string Units_Completed { get; set; }
        public Nullable<System.DateTime> Date_Completed { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public string CREP { get; set; }
        public string AWEP { get; set; }
        public string EQIP { get; set; }
        public Nullable<int> Base_Year { get; set; }
        public string impl_note_0 { get; set; }
        public string impl_tbi_0 { get; set; }
        public string impl_note_1 { get; set; }
        public string impl_tbi_1 { get; set; }
        public string impl_note_2 { get; set; }
        public string impl_tbi_2 { get; set; }
        public string impl_note_3 { get; set; }
        public string impl_tbi_3 { get; set; }
        public string impl_note_4 { get; set; }
        public string impl_tbi_4 { get; set; }
        public string impl_note_5 { get; set; }
        public string impl_tbi_5 { get; set; }
        public string impl_note_6 { get; set; }
        public string impl_tbi_6 { get; set; }
        public string impl_note_7 { get; set; }
        public string impl_tbi_7 { get; set; }
        public string impl_note_8 { get; set; }
        public string impl_tbi_8 { get; set; }
        public Nullable<int> Revision_Description { get; set; }
        public int pk_bmp_ag { get; set; }
        public Nullable<int> fk_supplementalAgreement { get; set; }
        public string fk_SAAssignType_code { get; set; }
        public string agreement_nbr_ro { get; set; }
    }
}
