//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_wfp6
    {
        public string Farm_No_ { get; set; }
        public string Farm_Listing { get; set; }
        public string Name__Participant_ { get; set; }
        public string Name__Producer_ { get; set; }
        public string Project_Location { get; set; }
        public string Project_Description { get; set; }
    }
}
