//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_wfp3
    {
        public string Farm_No_ { get; set; }
        public string Farm_Listing { get; set; }
        public string Participant_s_ { get; set; }
        public string address { get; set; }
        public string City_State { get; set; }
        public string Phone_No_ { get; set; }
        public string Planning_Team { get; set; }
        public string Package_Name { get; set; }
        public string Contract_Date { get; set; }
        public string Contract_Nbr { get; set; }
        public string Package_Date { get; set; }
        public string Special_Provisions { get; set; }
        public string Install_From { get; set; }
        public string Install_To { get; set; }
        public string Attached_Pages { get; set; }
        public string Procurement_Type { get; set; }
        public string Date { get; set; }
        public decimal Total_Design_Cost { get; set; }
        public int pk_form_wfp3 { get; set; }
    }
}
