//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDocumentFilepathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_wfp2_version
    {
        public int pk_farmBusiness { get; set; }
        public int pk_form_wfp2 { get; set; }
        public byte version { get; set; }
        public Nullable<System.DateTime> issued_date { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public decimal guideline { get; set; }
        public string note { get; set; }
        public string farmID { get; set; }
        public string farm_name { get; set; }
        public string ownerStr_dnd { get; set; }
        public string fk_status_code_curr { get; set; }
        public Nullable<int> fk_supplementalAgreement { get; set; }
        public string fk_farmSize_code { get; set; }
        public string fk_regionWAC_code { get; set; }
        public string ownerStrLF_dnd { get; set; }
        public string ownerStrFL_dnd { get; set; }
    }
}
