//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class bmp_ag
    {
        public bmp_ag()
        {
            this.BmpBacklog = new HashSet<BmpBacklog>();
            this.asrAg_bmp = new HashSet<asrAg_bmp>();
            this.bmp_ag13 = new HashSet<bmp_ag>();
            this.bmp_ag14 = new HashSet<bmp_ag>();
            this.bmp_ag15 = new HashSet<bmp_ag>();
            this.bmp_ag16 = new HashSet<bmp_ag>();
            this.bmp_ag_encumbrance = new HashSet<bmp_ag_encumbrance>();
            this.bmp_ag_funding = new HashSet<bmp_ag_funding>();
            this.bmp_ag_leasedLand = new HashSet<bmp_ag_leasedLand>();
            this.bmp_ag_location = new HashSet<bmp_ag_location>();
            this.bmp_ag_nmcp = new HashSet<bmp_ag_nmcp>();
            this.bmp_ag_note = new HashSet<bmp_ag_note>();
            this.bmp_ag_SA = new HashSet<bmp_ag_SA>();
            this.bmp_ag_status = new HashSet<bmp_ag_status>();
            this.bmp_ag_subIssue = new HashSet<bmp_ag_subIssue>();
            this.bmp_ag_subIssue1 = new HashSet<bmp_ag_subIssue>();
            this.bmp_ag_workload = new HashSet<bmp_ag_workload>();
            this.farmBusinessNMCP = new HashSet<farmBusinessNMCP>();
            this.farmBusinessNMP = new HashSet<farmBusinessNMP>();
            this.farmBusinessQMA = new HashSet<farmBusinessQMA>();
            this.farmBusinessWLProjectBMP = new HashSet<farmBusinessWLProjectBMP>();
            this.form_wfp3_bmp = new HashSet<form_wfp3_bmp>();
        }
    
        public int pk_bmp_ag { get; set; }
        public int fk_farmBusiness { get; set; }
        public string fk_pollutant_category_code { get; set; }
        public string bmp_nbr { get; set; }
        public string description { get; set; }
        public Nullable<byte> lifespan_year { get; set; }
        public Nullable<decimal> fk_bmpPractice_code { get; set; }
        public string location { get; set; }
        public Nullable<decimal> units_planned { get; set; }
        public string fk_unit_code { get; set; }
        public Nullable<decimal> est_plan_prior { get; set; }
        public Nullable<decimal> est_plan_rev { get; set; }
        public string component_nbr_legacy { get; set; }
        public string flood_2006 { get; set; }
        public string fk_bmpStatus2006_code { get; set; }
        public Nullable<int> fk_farmBusiness_implementation_transferred_from { get; set; }
        public Nullable<byte> QualifierVersion { get; set; }
        public string fk_procurementType_code { get; set; }
        public string bid_nbr_legacy { get; set; }
        public Nullable<decimal> design_cost { get; set; }
        public Nullable<decimal> final_modifications_cost { get; set; }
        public Nullable<decimal> final_cost { get; set; }
        public string fk_statusBMP_code { get; set; }
        public Nullable<int> fk_list_designerEngineer_engineer { get; set; }
        public Nullable<int> fk_list_designerEngineer_planner { get; set; }
        public string fk_agency_code_tech { get; set; }
        public string fk_revisionDescription_code { get; set; }
        public string revisionDescription_addl { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public string bmp_id_new_legacy { get; set; }
        public string CREP { get; set; }
        public string includeOnWFP2 { get; set; }
        public Nullable<int> fk_farmBusiness_implementation_transferred_to { get; set; }
        public Nullable<int> fk_list_designerEngineer_certifier { get; set; }
        public Nullable<int> fk_list_designerEngineer_inspector { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> fk_form_wfp2_version { get; set; }
        public string supplementalAttachmentWFP2 { get; set; }
        public Nullable<decimal> wac_appr_amt_orig_legacy { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string AWEP { get; set; }
        public string EQIP { get; set; }
        public Nullable<decimal> ABC { get; set; }
        public string validForABCCalc { get; set; }
        public string dimensions { get; set; }
        public Nullable<decimal> unit_est_planned_ro { get; set; }
        public Nullable<int> fk_programmaticRecord_code { get; set; }
        public string landowner_contribution { get; set; }
        public string fk_BMPSource_code { get; set; }
        public Nullable<decimal> units_completed { get; set; }
        public string fk_SAAssignType_code { get; set; }
        public Nullable<int> fk_supplementalAgreementTaxParcel { get; set; }
        public string description_short { get; set; }
        public Nullable<int> fk_bmp_ag_ancestor { get; set; }
        public Nullable<int> fk_bmp_ag_transferredTo { get; set; }
        public Nullable<int> fk_bmp_ag_transferredFrom { get; set; }
        public string SAStr_ro { get; set; }
        public string SATPStr_ro { get; set; }
        public Nullable<decimal> units_designed { get; set; }
        public string dimensions_designed { get; set; }
        public string fk_BMPTypeCode { get; set; }
        public string issueStatement_wfp2 { get; set; }
        public string fk_BMPCode_code { get; set; }
        public string fk_BMPCREPH20_code { get; set; }
        public Nullable<int> fk_bmp_ag_subIssueHeader { get; set; }
        public Nullable<short> NMCP_yr { get; set; }
        public string TaxParcels { get; set; }
        public Nullable<int> fk_farmBusinessWLProject { get; set; }
        public string Bmp { get; set; }
        public Nullable<int> AgBmpViabilityCodeId { get; set; }
        public string CompositBmpNum { get; set; }
        public Nullable<int> AgBmpDescriptorCodeId { get; set; }
    
        public virtual ICollection<BmpBacklog> BmpBacklog { get; set; }
        public virtual ICollection<asrAg_bmp> asrAg_bmp { get; set; }
        public virtual AgBmpViabilityCode AgBmpViabilityCode { get; set; }
        public virtual bmp_ag bmp_ag1 { get; set; }
        public virtual bmp_ag bmp_ag2 { get; set; }
        public virtual bmp_ag bmp_ag11 { get; set; }
        public virtual bmp_ag bmp_ag3 { get; set; }
        public virtual bmp_ag bmp_ag12 { get; set; }
        public virtual bmp_ag bmp_ag4 { get; set; }
        public virtual ICollection<bmp_ag> bmp_ag13 { get; set; }
        public virtual bmp_ag bmp_ag5 { get; set; }
        public virtual ICollection<bmp_ag> bmp_ag14 { get; set; }
        public virtual bmp_ag bmp_ag6 { get; set; }
        public virtual ICollection<bmp_ag> bmp_ag15 { get; set; }
        public virtual bmp_ag bmp_ag7 { get; set; }
        public virtual ICollection<bmp_ag> bmp_ag16 { get; set; }
        public virtual bmp_ag bmp_ag8 { get; set; }
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual farmBusiness farmBusiness1 { get; set; }
        public virtual farmBusiness farmBusiness2 { get; set; }
        public virtual farmBusinessWLProject farmBusinessWLProject { get; set; }
        public virtual list_BMPCode list_BMPCode { get; set; }
        public virtual list_BMPCREPH20 list_BMPCREPH20 { get; set; }
        public virtual list_bmpPractice list_bmpPractice { get; set; }
        public virtual list_BMPSource list_BMPSource { get; set; }
        public virtual list_bmpStatus2006 list_bmpStatus2006 { get; set; }
        public virtual list_designerEngineer list_designerEngineer { get; set; }
        public virtual list_designerEngineer list_designerEngineer1 { get; set; }
        public virtual list_designerEngineer list_designerEngineer2 { get; set; }
        public virtual list_designerEngineer list_designerEngineer3 { get; set; }
        public virtual list_lifespan list_lifespan { get; set; }
        public virtual list_pollutant_category list_pollutant_category { get; set; }
        public virtual list_procurementType list_procurementType { get; set; }
        public virtual list_programmaticRecord list_programmaticRecord { get; set; }
        public virtual list_revisionDescription list_revisionDescription { get; set; }
        public virtual list_SAAssignType list_SAAssignType { get; set; }
        public virtual list_statusBMP list_statusBMP { get; set; }
        public virtual list_unit list_unit { get; set; }
        public virtual supplementalAgreementTaxParcel supplementalAgreementTaxParcel { get; set; }
        public virtual ICollection<bmp_ag_encumbrance> bmp_ag_encumbrance { get; set; }
        public virtual ICollection<bmp_ag_funding> bmp_ag_funding { get; set; }
        public virtual ICollection<bmp_ag_leasedLand> bmp_ag_leasedLand { get; set; }
        public virtual ICollection<bmp_ag_location> bmp_ag_location { get; set; }
        public virtual ICollection<bmp_ag_nmcp> bmp_ag_nmcp { get; set; }
        public virtual ICollection<bmp_ag_note> bmp_ag_note { get; set; }
        public virtual ICollection<bmp_ag_SA> bmp_ag_SA { get; set; }
        public virtual ICollection<bmp_ag_status> bmp_ag_status { get; set; }
        public virtual ICollection<bmp_ag_subIssue> bmp_ag_subIssue { get; set; }
        public virtual ICollection<bmp_ag_subIssue> bmp_ag_subIssue1 { get; set; }
        public virtual ICollection<bmp_ag_workload> bmp_ag_workload { get; set; }
        public virtual ICollection<farmBusinessNMCP> farmBusinessNMCP { get; set; }
        public virtual ICollection<farmBusinessNMP> farmBusinessNMP { get; set; }
        public virtual ICollection<farmBusinessQMA> farmBusinessQMA { get; set; }
        public virtual ICollection<farmBusinessWLProjectBMP> farmBusinessWLProjectBMP { get; set; }
        public virtual ICollection<form_wfp3_bmp> form_wfp3_bmp { get; set; }
    }
}
