//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class bmpbacklogbackup
    {
        public int BmpBacklogId { get; set; }
        public int fk_bmp_ag { get; set; }
        public int fk_farmBusiness { get; set; }
        public Nullable<System.DateTime> BacklogSnapshotDate { get; set; }
        public Nullable<System.DateTime> IRCDate { get; set; }
        public Nullable<System.DateTime> BMPDate { get; set; }
    }
}
