//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmBusinessWLProject
    {
        public farmBusinessWLProject()
        {
            this.bmp_ag = new HashSet<bmp_ag>();
            this.farmBusinessWLProjectBMP = new HashSet<farmBusinessWLProjectBMP>();
        }
    
        public int pk_farmBusinessWLProject { get; set; }
        public int fk_farmBusiness { get; set; }
        public string alias { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string project_code { get; set; }
        public Nullable<short> design_year { get; set; }
        public Nullable<short> build_year { get; set; }
        public Nullable<short> ImplementationProject { get; set; }
    
        public virtual ICollection<bmp_ag> bmp_ag { get; set; }
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual ICollection<farmBusinessWLProjectBMP> farmBusinessWLProjectBMP { get; set; }
    }
}
