//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmLandTractField
    {
        public farmLandTractField()
        {
            this.bmp_ag_location = new HashSet<bmp_ag_location>();
        }
    
        public int pk_farmLandTractField { get; set; }
        public int fk_farmLandTract { get; set; }
        public Nullable<short> year { get; set; }
        public string field { get; set; }
        public string tractField { get; set; }
        public string soil { get; set; }
        public Nullable<decimal> area { get; set; }
        public Nullable<decimal> acres { get; set; }
        public Nullable<decimal> perimeter { get; set; }
        public string note { get; set; }
        public string availableToRent { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
    
        public virtual ICollection<bmp_ag_location> bmp_ag_location { get; set; }
        public virtual farmLandTract farmLandTract { get; set; }
    }
}
