//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmBusinessTier1
    {
        public farmBusinessTier1()
        {
            this.farmBusinessTier1Animal = new HashSet<farmBusinessTier1Animal>();
        }
    
        public int pk_farmBusinessTier1 { get; set; }
        public int fk_farmBusiness { get; set; }
        public Nullable<decimal> tier2_points { get; set; }
        public string farm_descrip { get; set; }
        public Nullable<decimal> acres_total { get; set; }
        public Nullable<decimal> acres_rent { get; set; }
        public Nullable<decimal> acres_forest { get; set; }
        public Nullable<decimal> acres_till { get; set; }
        public Nullable<decimal> acres_till_rent { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string farmNameLocation { get; set; }
        public string GIS_nbr_legacy { get; set; }
        public string eoh_id_legacy { get; set; }
        public string eoh_income1K { get; set; }
        public Nullable<System.DateTime> eoh_lastUpdate { get; set; }
        public Nullable<decimal> acres_hay { get; set; }
        public Nullable<decimal> acres_pasture { get; set; }
        public Nullable<decimal> eoh_au_manual { get; set; }
        public Nullable<int> ranking { get; set; }
        public Nullable<System.DateTime> tier1_recd { get; set; }
        public Nullable<System.DateTime> tier2_recd { get; set; }
        public string eoh_income5K { get; set; }
    
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual ICollection<farmBusinessTier1Animal> farmBusinessTier1Animal { get; set; }
    }
}
