//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmBusinessNote
    {
        public int pk_farmBusinessNote { get; set; }
        public int fk_farmBusiness { get; set; }
        public string note { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public string fk_farmBusinessNoteType_code { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
    
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual list_farmBusinessNoteType list_farmBusinessNoteType { get; set; }
    }
}
