//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmBusinessCREP
    {
        public int pk_farmBusinessCREP { get; set; }
        public int fk_farmBusiness { get; set; }
        public string owner_FSA { get; set; }
        public string contract { get; set; }
        public string term { get; set; }
        public Nullable<decimal> acreage { get; set; }
        public Nullable<System.DateTime> expiration { get; set; }
        public Nullable<int> expiration_year { get; set; }
        public string planner_NRCS { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public Nullable<int> fk_supplementalAgreement { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> fk_list_designerEngineer { get; set; }
    
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual list_designerEngineer list_designerEngineer { get; set; }
        public virtual supplementalAgreement supplementalAgreement { get; set; }
    }
}
