//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmFarmBusinessLink
    {
        public int PkFarmFarmBusinessLink { get; set; }
        public Nullable<int> fk_farmBusiness { get; set; }
        public Nullable<int> FkFarm { get; set; }
        public Nullable<System.DateTime> approved_date_legacy { get; set; }
        public string fk_groupPI_code { get; set; }
        public Nullable<decimal> gps_id_legacy { get; set; }
    }
}
