//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmBusinessLandBaseInfo
    {
        public int pk_farmBusinessLandBaseInfo { get; set; }
        public int fk_farmBusiness { get; set; }
        public Nullable<decimal> acreage_own_total { get; set; }
        public Nullable<decimal> acreage_rent_total { get; set; }
        public Nullable<decimal> rotated_row_crop_own { get; set; }
        public string crop_description { get; set; }
        public Nullable<decimal> hayland_permanent { get; set; }
        public Nullable<decimal> pasture_permanent { get; set; }
        public Nullable<decimal> paddock_cnt { get; set; }
        public Nullable<decimal> ridingRing_cnt { get; set; }
        public Nullable<decimal> woodland_acre { get; set; }
        public Nullable<decimal> scrubland_acre { get; set; }
        public Nullable<decimal> farmstead_acre { get; set; }
        public Nullable<decimal> residential_acre { get; set; }
        public Nullable<decimal> cropland_acre_rent { get; set; }
        public string crop_description_rent { get; set; }
        public Nullable<decimal> hayland_acre_rent { get; set; }
        public Nullable<decimal> pasture_acre_rent { get; set; }
        public Nullable<decimal> woodland_acre_rent { get; set; }
        public string forested { get; set; }
        public string commitment_480A { get; set; }
        public string comment { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public Nullable<int> barnToH2O_ft { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> pollutantCategoryTop3ToH20_ft { get; set; }
        public string fk_basin_code_priorityEOH { get; set; }
        public Nullable<decimal> other_acre { get; set; }
        public Nullable<decimal> other_acre_rent { get; set; }
        public Nullable<decimal> crop_acre { get; set; }
        public Nullable<decimal> hay_acre { get; set; }
        public Nullable<decimal> pasture_acre { get; set; }
        public Nullable<decimal> crop_acre_rent { get; set; }
        public Nullable<decimal> hay_acre_rent { get; set; }
        public Nullable<decimal> acre_rent_total { get; set; }
        public Nullable<decimal> acre_total { get; set; }
        public Nullable<int> fieldDistanceToH20_eoh { get; set; }
        public Nullable<decimal> taxParcel_acre { get; set; }
        public Nullable<int> farmRankingProfJudgement_eoh { get; set; }
    
        public virtual farmBusiness farmBusiness { get; set; }
        public virtual list_basin list_basin { get; set; }
    }
}
