//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_wfp3_payment
    {
        public form_wfp3_payment()
        {
            this.form_wfp3_paymentBMP = new HashSet<form_wfp3_paymentBMP>();
        }
    
        public int pk_form_wfp3_payment { get; set; }
        public int fk_form_wfp3 { get; set; }
        public Nullable<int> fk_participant_payee { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> amt { get; set; }
        public string check_nbr { get; set; }
        public string fk_encumbrance_code { get; set; }
        public string note { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public string bmp_nbr_new_legacy { get; set; }
        public Nullable<int> contractor_id_legacy { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string component_nbr_legacy { get; set; }
        public Nullable<int> fk_form_wfp3_invoice { get; set; }
    
        public virtual form_wfp3 form_wfp3 { get; set; }
        public virtual form_wfp3_invoice form_wfp3_invoice { get; set; }
        public virtual list_encumbrance list_encumbrance { get; set; }
        public virtual participant participant { get; set; }
        public virtual ICollection<form_wfp3_paymentBMP> form_wfp3_paymentBMP { get; set; }
    }
}
