//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_groupPIMember
    {
        public int pk_list_groupPIMember { get; set; }
        public string fk_groupPI_code { get; set; }
        public int fk_list_designerEngineer { get; set; }
        public string groupLeader { get; set; }
        public string @float { get; set; }
    
        public virtual list_designerEngineer list_designerEngineer { get; set; }
        public virtual list_groupPI list_groupPI { get; set; }
    }
}
