//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_asrAgChanges
    {
        public list_asrAgChanges()
        {
            this.asrAg_changes = new HashSet<asrAg_changes>();
            this.asrAg_changes1 = new HashSet<asrAg_changes>();
        }
    
        public string pk_asrAgChanges_code { get; set; }
        public string process { get; set; }
        public string mode { get; set; }
    
        public virtual ICollection<asrAg_changes> asrAg_changes { get; set; }
        public virtual ICollection<asrAg_changes> asrAg_changes1 { get; set; }
    }
}
