//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_interest
    {
        public list_interest()
        {
            this.list_interestType = new HashSet<list_interestType>();
        }
    
        public int pk_list_interest { get; set; }
        public string interest { get; set; }
        public string active { get; set; }
        public string fk_interestBase_code { get; set; }
    
        public virtual list_interestBase list_interestBase { get; set; }
        public virtual ICollection<list_interestType> list_interestType { get; set; }
    }
}
