//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_maritalStatus
    {
        public list_maritalStatus()
        {
            this.participantWAC = new HashSet<participantWAC>();
        }
    
        public string pk_maritalStatus_code { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<participantWAC> participantWAC { get; set; }
    }
}
