//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_reportGroup
    {
        public list_reportGroup()
        {
            this.userReportGroup = new HashSet<userReportGroup>();
        }
    
        public string pk_reportGroup_code { get; set; }
        public string reportGroup { get; set; }
    
        public virtual ICollection<userReportGroup> userReportGroup { get; set; }
    }
}
