//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_agWorkloadFunding
    {
        public list_agWorkloadFunding()
        {
            this.agWorkloadFunding = new HashSet<agWorkloadFunding>();
            this.bmp_ag_workload = new HashSet<bmp_ag_workload>();
        }
    
        public string pk_agWorkloadFunding_code { get; set; }
        public string source { get; set; }
    
        public virtual ICollection<agWorkloadFunding> agWorkloadFunding { get; set; }
        public virtual ICollection<bmp_ag_workload> bmp_ag_workload { get; set; }
    }
}
