//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_fiscalYear
    {
        public list_fiscalYear()
        {
            this.participantWAC_evaluation = new HashSet<participantWAC_evaluation>();
            this.participantWAC_training = new HashSet<participantWAC_training>();
        }
    
        public string pk_fiscalYear_code { get; set; }
        public string fiscalYear { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual ICollection<participantWAC_evaluation> participantWAC_evaluation { get; set; }
        public virtual ICollection<participantWAC_training> participantWAC_training { get; set; }
    }
}
