//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_eventSponsor
    {
        public list_eventSponsor()
        {
            this.eventName = new HashSet<eventName>();
        }
    
        public string pk_eventSponsor_code { get; set; }
        public string sponsor { get; set; }
    
        public virtual ICollection<eventName> eventName { get; set; }
    }
}
