//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_eventRegistrantType
    {
        public list_eventRegistrantType()
        {
            this.eventRegistrant = new HashSet<eventRegistrant>();
        }
    
        public string pk_eventRegistrantType_code { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<eventRegistrant> eventRegistrant { get; set; }
    }
}
