//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_AMLPriority
    {
        public list_AMLPriority()
        {
            this.mailingParticipant = new HashSet<mailingParticipant>();
        }
    
        public int pk_AMLPriority_code { get; set; }
        public string priority_level { get; set; }
    
        public virtual ICollection<mailingParticipant> mailingParticipant { get; set; }
    }
}
