//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_encumbranceType
    {
        public list_encumbranceType()
        {
            this.form_wfp3_encumbrance = new HashSet<form_wfp3_encumbrance>();
        }
    
        public string pk_encumbranceType_code { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<form_wfp3_encumbrance> form_wfp3_encumbrance { get; set; }
    }
}
