//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_letter
    {
        public string pk_letter_code { get; set; }
        public string letter { get; set; }
        public string easement { get; set; }
        public string agriculture { get; set; }
        public string forestry { get; set; }
    }
}
