//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_participantTypeSector
    {
        public list_participantTypeSector()
        {
            this.list_participantTypeSectorFolder = new HashSet<list_participantTypeSectorFolder>();
        }
    
        public string pk_participantTypeSector_code { get; set; }
        public string fk_participantType_code { get; set; }
        public string sector { get; set; }
    
        public virtual list_participantType list_participantType { get; set; }
        public virtual ICollection<list_participantTypeSectorFolder> list_participantTypeSectorFolder { get; set; }
    }
}
