//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_nrcs_code
    {
        public decimal pk_nrcsCode { get; set; }
        public string practice { get; set; }
        public Nullable<byte> life_reqd_year { get; set; }
        public string agronomic { get; set; }
        public string fk_unit_code { get; set; }
        public string wac_category { get; set; }
    }
}
