//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_sisterAgencyTitle
    {
        public list_sisterAgencyTitle()
        {
            this.list_designerEngineer = new HashSet<list_designerEngineer>();
        }
    
        public string pk_sisterAgencyTitle_code { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<list_designerEngineer> list_designerEngineer { get; set; }
    }
}
