//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_forestryCode
    {
        public list_forestryCode()
        {
            this.participantForestryType = new HashSet<participantForestryType>();
        }
    
        public string pk_forestryCode_code { get; set; }
        public string description { get; set; }
        public string contractor { get; set; }
    
        public virtual ICollection<participantForestryType> participantForestryType { get; set; }
    }
}
