//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_pollutant_category
    {
        public list_pollutant_category()
        {
            this.bmp_ag = new HashSet<bmp_ag>();
        }
    
        public string pk_pollutant_category_code { get; set; }
        public Nullable<short> pollutant_category_nbr { get; set; }
        public string descrip { get; set; }
        public string crep { get; set; }
        public Nullable<int> sort_position { get; set; }
    
        public virtual ICollection<bmp_ag> bmp_ag { get; set; }
    }
}
