//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_animalAge
    {
        public list_animalAge()
        {
            this.farmBusinessAnimalAge = new HashSet<farmBusinessAnimalAge>();
        }
    
        public int pk_list_animalAge { get; set; }
        public string ageBracket { get; set; }
    
        public virtual ICollection<farmBusinessAnimalAge> farmBusinessAnimalAge { get; set; }
    }
}
