//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class participantWAC_training
    {
        public participantWAC_training()
        {
            this.participantWAC_trainingCost = new HashSet<participantWAC_trainingCost>();
        }
    
        public int pk_participantWAC_training { get; set; }
        public int fk_participantWAC { get; set; }
        public string fk_trainingReqd_code { get; set; }
        public string fk_positionWAC_code { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string note { get; set; }
        public string fk_fiscalYear_code { get; set; }
    
        public virtual list_fiscalYear list_fiscalYear { get; set; }
        public virtual list_positionWAC list_positionWAC { get; set; }
        public virtual list_trainingReqd list_trainingReqd { get; set; }
        public virtual participantWAC participantWAC { get; set; }
        public virtual ICollection<participantWAC_trainingCost> participantWAC_trainingCost { get; set; }
    }
}
