//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class participantProperty
    {
        public int pk_participantProperty { get; set; }
        public int fk_participant { get; set; }
        public int fk_property { get; set; }
        public string master { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> fk_participant_cc { get; set; }
        public string note { get; set; }
    
        public virtual participant participant { get; set; }
        public virtual participant participant1 { get; set; }
        public virtual property property { get; set; }
    }
}
