//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class participantWAC_position
    {
        public int pk_participantWAC_position { get; set; }
        public int fk_participantWAC { get; set; }
        public string fk_positionWAC_code { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public Nullable<decimal> salary_begin { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> exitInterview_date { get; set; }
        public string exitInterview_note { get; set; }
    
        public virtual list_positionWAC list_positionWAC { get; set; }
        public virtual participantWAC participantWAC { get; set; }
    }
}
