//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_FarmDocumentFilePathUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxParcelReference
    {
        public string printKey { get; set; }
        public string SBL { get; set; }
        public string fk_list_swis { get; set; }
        public int pk_taxParcelReference { get; set; }
    }
}
